### ISSUE TITLE
install POX

### ISSUE THREAD

**Issue by jungyuLiao** [noxrepo/pox#112]
I'm beginner to used pox, when i install the pox, it show the error message:
INFO:core:POX 0.2.0 (carp) is up.
ERROR:openflow.of_01:Error 99 while binding socket: Cannot assign requested address
ERROR:openflow.of_01: You may be specifying a local address which is not assigned to any interface.

what can i do?
thanks

**Comment by MurphyMc** [comment]
Please...

Post the commandline with which you invoked POX.
Post the log at DEBUG level.

(See the final question on the POX FAQ for these and more time-saving tips on getting help.)

**Comment by MurphyMc** [comment]
Idle for two weeks and probably more of a question for pox-dev or the POX forum on noxrepo.org anyway.  Closing.  (Reopen if necessary)

**Comment by SadhuRamBasnet** [comment]
I am also beginner to POX. I write following command in the terminal [commandline].

cd pox
./pox.py openflow.of_01 --address=10.1.1.1 --port=6634

But I also get the following error message

INFO:core:POX 0.2.0 (carp) is up.
ERROR:openflow.of_01:Error 99 while binding socket: Cannot assign requested address
ERROR:openflow.of_01: You may be specifying a local address which is not assigned to any interface.

What can I do to remove it?

**Comment by MurphyMc** [comment]
Remove the --address=10.1.1.1.  Is there any reason you are specifying that?  Or any reason you're specifying port 6634?

Also, you're not actually specifying any component which actually does anything in that commandline, so POX won't be very interesting.  I suggest that you might want to look through the early sections of the POX manual if you haven't already -- particularly the section on invoking POX.

**Comment by SadhuRamBasnet** [comment]
Thank you Sir ! I will go through the POX manual available from 
https://openflow.stanford.edu/display/ONL/POX+Wiki
