### ISSUE TITLE
Extract mac header in pox

### ISSUE THREAD

**Issue by namrah16** [noxrepo/pox#115]
Hi, I'm working on wireless in pox. I want to extract the mac header of 802.11 of the packets that arrive at the controller. I cannot find a way to do that, I can extract the Ethernet header but that only gives me the mac addresses and the type, I need to extract the frame control bytes. Can someone please help me with this. Any help is appreciated. Thank you in advance.

**Comment by MurphyMc** [comment]
I don't think there's an obvious way to do this.  At least up through OpenFlow 1.3, a packet in OpenFlow is an Ethernet packet.  The wireless header is already gone way before the packet reaches the controller.

**Comment by namrah16** [comment]
So there is no way i can get the wireless header then?

**Comment by MurphyMc** [comment]
Not so far as I know without at least modifying the switch or doing other tricks somewhere (e.g., encapsulating the wireless frames).  Either of which are outside the scope of POX.  The openflow-discuss mailing list may be a better resource.

**Comment by namrah16** [comment]
Ok Thank you for your reply :)
