### ISSUE TITLE
PoX connection errors

### ISSUE THREAD

**Issue by oadele3** [noxrepo/pox#126]
I am trying to connect an OVS on linux box to a remote POX controller. 

I tried running the learning_switch example. encountered errors (shown below) what could be the cause of these? and how do I solve them? please this is v.urgent.

=============================== terminal output ===========================

root@controller:~/pox# ./pox.py samples.pretty_log forwarding.l2_learning
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
[core                   ] POX 0.2.0 (carp) is up.
[openflow.of_01         ] Exception reading connection [None 1]
Traceback (most recent call last):
  File "/users/oadele3/pox/pox/openflow/of_01.py", line 912, in run
    if con.read() is False:
  File "/users/oadele3/pox/pox/openflow/of_01.py", line 751, in read
    new_offset,msg = unpackers[ofp_type](self.buf, offset)
  File "/users/oadele3/pox/pox/openflow/libopenflow_01.py", line 197, in unpack_
    assert (r-offset) == length, o
AssertionError: ofp_hello
  header:
    version: 4
    type:    0 (OFPT_HELLO)
    length:  8
    xid:     5
[openflow.of_01         ] [None 1] closed

======================== end of terminal output =========================

please how do I solve this problem
-mayowa

**Comment by MurphyMc** [comment]
Best guess is that the switch is configured for OpenFlow 1.3, but POX currently only supports 1.0.

**Comment by oadele3** [comment]
thank you very much that really helped

I can connect now

On Wed, Sep 17, 2014 at 9:46 PM, Murphy notifications@github.com wrote:

> Best guess is that the switch is configured for OpenFlow 1.3, but POX
> currently only supports 1.0.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/noxrepo/pox/issues/126#issuecomment-55988801.

## 

_Adeleke Oluwamayowa_

_+1 312 479 8288_

**Comment by MurphyMc** [comment]
Since this is unrelated, please file it as a new issue.  Or better yet, post it to the pox-dev mailing list.

**Comment by senthilkuma** [comment]
i could not connect to POX controller

**Comment by oadele3** [comment]
Hi.

It means that there is a controller process associated with that
port already running, which needs to be closed.

You can enter this command to end it

#sudo fuser -k 6633/tcp

Then you can start the process again

-Mayowa

On Sunday, October 5, 2014, senthilkuma notifications@github.com wrote:

> i could not connect to POX controller
> 
> On Sun, Oct 5, 2014 at 12:04 PM, Murphy <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Closed #126 https://github.com/noxrepo/pox/issues/126.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/noxrepo/pox/issues/126#event-174215143.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/noxrepo/pox/issues/126#issuecomment-57927335.

## 

_Adeleke Oluwamayowa_

_+1 312 479 8288_

**Comment by senthilkuma** [comment]
hai dear
i killed those controler using your command
but after that i put command for start controller it shows nothing....

root@ubuntu:~/pox# ./pox.py
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
INFO:core:POX 0.2.0 (carp) is up.

here after it shows nothing....it didnt show any error.............and any results......

can you please help me.........

**Comment by vieangry** [comment]
@oadele3  I also encountered this problem, I want to know how you solved it?

POX 0.5.0 (eel) / Copyright 2011-2014 James McCauley, et al.
DEBUG:core:POX 0.5.0 (eel) going up...
DEBUG:core:Running on CPython (2.7.12/Nov 12 2018 14:36:49)
DEBUG:core:Platform is Linux-4.15.0-46-generic-x86_64-with-Ubuntu-16.04-xenial
INFO:core:POX 0.5.0 (eel) is up.
DEBUG:openflow.of_01:Listening on 0.0.0.0:6633
ERROR:openflow.of_01:Exception reading connection [None 1]
Traceback (most recent call last):
  File "/home/ubuntu/pox/pox/openflow/of_01.py", line 1132, in run
    if con.read() is False:
  File "/home/ubuntu/pox/pox/openflow/of_01.py", line 926, in read
    new_offset,msg = self.unpackers[ofp_type](self.buf, offset)
  File "/home/ubuntu/pox/pox/openflow/libopenflow_01.py", line 197, in unpack_new
    assert (r-offset) == length, o
AssertionError: ofp_hello
  header: 
    version: 4
    type:    0 (OFPT_HELLO)
    length:  8
    xid:     880
ERROR:openflow.of_01:Exception reading connection [None 2]
Traceback (most recent call last):
  File "/home/ubuntu/pox/pox/openflow/of_01.py", line 1132, in run
    if con.read() is False:
  File "/home/ubuntu/pox/pox/openflow/of_01.py", line 926, in read
    new_offset,msg = self.unpackers[ofp_type](self.buf, offset)
  File "/home/ubuntu/pox/pox/openflow/libopenflow_01.py", line 197, in unpack_new
    assert (r-offset) == length, o
AssertionError: ofp_hello

**Comment by MurphyMc** [comment]
As in the first reply, the issue here is likely that Open vSwitch is talking a version of OpenFlow that POX doesn't understand (see the "version: 4" in the error messages).  Configure OVS to speak OpenFlow 1.0, as per [the OVS documentation](http://docs.openvswitch.org/en/latest/faq/openflow/).  For example, for a datapath named br0, use ovs-vsctl to set OpenFlow 1.0 only:
```
ovs-vsctl set bridge br0 protocols=OpenFlow10
```
