### ISSUE TITLE
ARP Request and ARP Reply in Pox

### ISSUE THREAD

**Issue by charlesturyagyenda** [noxrepo/pox#137]
The following command produces the same output value for both ARP Requests and ARP Replies

event.parsed.type

This produces a value of 2054 for both ARP Requests and Replies

I believe this command should produce a value of 32821 for ARP replies and 2054 for ARP requests

**Comment by MurphyMc** [comment]
I think you're confusing ARP replies (distinguished from an ARP request via the operation field in the ARP packet) and Reverse ARP (an obsolete predecessor to DHCP which happens to use the same packet layout as ARP and distinguishable by a different ethertype).

**Comment by charlesturyagyenda** [comment]
Thank you for the clarification. How do I  access the operation field value?

Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Murphy notifications@github.com </div><div>Date:28/02/2015  01:32  (GMT+00:00) </div><div>To: noxrepo/pox pox@noreply.github.com </div><div>Cc: charlesturyagyenda turchaj@yahoo.com </div><div>Subject: Re: [pox] ARP Request and ARP Reply in Pox (#137) </div><div>
</div>I think you're confusing ARP replies (distinguished from an ARP request via the operation field in the ARP packet) and Reverse ARP (an obsolete predecessor to DHCP which happens to use the same packet layout as ARP and distinguishable by a different ethertype).

**Comment by MurphyMc** [comment]
I think there's a reasonably clear example in the ["Example: ARP Messages"](https://openflow.stanford.edu/display/ONL/POX+Wiki#POXWiki-Example%3AARPmessages) section of the manual.

You can also check out the code, for example [here](https://github.com/noxrepo/pox/blob/eel/pox/lib/packet/arp.py#L62) and [here](https://github.com/noxrepo/pox/blob/eel/pox/lib/packet/arp.py#L159).

**Comment by charlesturyagyenda** [comment]
Thank you kind Sir. You have been most helpful.
Charles 

Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Murphy notifications@github.com </div><div>Date:28/02/2015  08:36  (GMT+00:00) </div><div>To: noxrepo/pox pox@noreply.github.com </div><div>Cc: charlesturyagyenda turchaj@yahoo.com </div><div>Subject: Re: [pox] ARP Request and ARP Reply in Pox (#137) </div><div>
</div>I think there's a reasonably clear example in the "Example: ARP Messages" section of the manual.

You can also check out the code, for example here and here.
