### ISSUE TITLE
How to split traffic in pox controller between ports at switch

### ISSUE THREAD

**Issue by athyagat** [noxrepo/pox#141]
Hi, 

We are trying to develop a load balancer in pox controller, after evaluating statistics at traffic shaping (TS)  nodes, we want to split the traffic at the switch between two ports

After researching through the pox controller examples, we were not able to find an example which splits the incoming traffic, based on percentage or evenly.

Can someone help direct us ?

Thanks,

**Comment by ZafarHussain88** [comment]
Hi Athyagat,

did you get what you were doing? i am asking this because i am trying the same thing and i am also lost. if you have done it already, can you please share your findings?

**Comment by athyagat** [comment]
Hi Zafar,

No. We had to change our problem statement, since I didn't find any
solutions for it.

Thanks,
Akhilesh

**Comment by abuamara** [comment]
Hello there
I have developed a traffic steering systems, based on link utilisation, my controller will instruct the switch to steer a specific Vlan to another port based on threshold value. Now I am building an algorithm of a load balance to kick in after the steering is done.
