### ISSUE TITLE
POX formatting and style is not PEP8

### ISSUE THREAD

**Issue by jameskyle** [noxrepo/pox#144]
Much of the source has formatting that does not conform to the PEP8 style guide. Most programming editors automatically format Python code according to PEP8 when the file type is detected.

Following PEP8 formatting would create an easier development environment for most python programmers and reduce probability of inconsistent formatting (I assume this is why the conversion script to retab everything is in the project).

Reference: https://www.python.org/dev/peps/pep-0008/#indentation

**Comment by nemethf** [comment]
I think this is more or less answered on the wiki: 
https://openflow.stanford.edu/display/ONL/POX+Wiki#POXWiki-CodingConventions

(Regarding the editors, Emacs recognizes if a file uses two spaces for indentation, and follows this file local convention.)

**Comment by jameskyle** [comment]
It seems an odd decision, but fair enough.
