### ISSUE TITLE
Question/possible bug in link event handling in forwarding.l2_multi, dart branch

### ISSUE THREAD

**Issue by MR-KO** [noxrepo/pox#148]
Sorry if this may not be up to standards (this is my first time posting), but in the code of l2_multi.py (pox/forwarding/l2_multi.py, using the dart branch), I noticed this, in the function

```
  def _handle_openflow_discovery(self, event):
        <code>
        # If we already consider these nodes connected, we can ignore this link up.
        # Otherwise, we might be interested...
        if adjacency[sw1][sw2] is None:
              # These previously weren't connected.  If the link
              # exists in both directions, we consider them connected now.
              if flip(l) in core.openflow_discovery.adjacency:
                    # Yup, link goes both ways -- connected!
                    adjacency[sw1][sw2] = l.port1
                    adjacency[sw2][sw1] = l.port2
```

But why is the link only added to the adjacency matrix if it goes both ways? Why not add a 1-way link already, no matter if it goes in both directions? So then it would be more like this:

```
  def _handle_openflow_discovery:
        <code>
        # If we already consider these nodes connected, we can ignore this link up.
        # Otherwise, we might be interested...
        if adjacency[sw1][sw2] is None:
              # These previously weren't connected.  If the link
              # exists in both directions, we consider them connected now.
              adjacency[sw1][sw2] = l.port1

              if flip(l) in core.openflow_discovery.adjacency:
                    # Yup, link goes both ways -- connected!
                    adjacency[sw2][sw1] = l.port2
              else:
                    adjacency[sw2][sw1] = None  # The link in the other direction does not exist
```

**Comment by MurphyMc** [comment]
Before 118edac42e4f78be6df358c8da1bc746ca54f776, it actually did both directions independently.  It was a couple years ago, so my memory is sketchy, but I don't remember there being a single big reason for that particular change.  I think it just made it more straightforward and easier to reason about.  Which is probably true in several ways.  If you Wireshark a link and see the traffic in one direction, you'll see the other.  If you see the SYNs getting to a host, you know there should be a path back for the SYNACKs.  Etc.

Is there any big advantage to doing it unidirectionally for common use cases?

**Comment by MR-KO** [comment]
I can't think of an advantage to doing it unidirectionally for common cases (other than the fact that links between switches rarely only go 1 way), but neither do I see any disadvantage in already adding one way of the link, and only adding the other part if it actually exists. I guess this is a matter of perspective.

I'm currently experimenting with mininet and writing my own POX module to do some multipath routing based on free bandwidth on links. If host A sends a flow of packets to host B, my method could use a different path from B to A than from A to B, based on some decision making. So monitoring one link on the path from A to B may not show the flow back to A, as that flow takes a different path. Then again, this is not really a common use case. Anyway, thanks for the quick clarification.
