### ISSUE TITLE
Wiki typo on the core.openflow sec

### ISSUE THREAD

**Issue by francozappa** [noxrepo/pox#151]
correct
... and there is a `.dpids()` attribute which is really the same as `.keys()`

with
... and there is a `.dpids` attribute which store the same `list` produced by `.keys()` (that is a `dict` built-in method, not an attribute) 

error report:
`File "/home/mel/pox/ext/l2_pairs.py", line 194, in _enumerate_datapaths
    dpids = nexus.connections.dpids()
TypeError: 'list' object is not callable
`

**Comment by MurphyMc** [comment]
Fixed this in the Sphinx version of the manual (which I'll be putting up as soon as I have the time).

Thanks!

(Will leave issue open until I actually post the new documentation.)

**Comment by MurphyMc** [comment]
Closing this, since the new documentation has been up forever and it's fixed in the RST source.  It looks like the HTML needs to be regenerated from the RST, but that's a separate issue. :)
