### ISSUE TITLE
Flow installation time

### ISSUE THREAD

**Issue by hadik3r** [noxrepo/pox#161]
I am trying to measure the time of installing flow rules into an OVS switch flow table using Pox controller. To measure the time, I generate packets at different rates and send them through the OVS switch. To forward each packet the switch needs to ask the controller (send a packet_in to the controller). I measure the time between the packet arriving at one port of the switch and the time it leaves the switch through another port (using wireshark). However, surprisingly as I increase the packet generation rate, the time needed to forward packet becomes shorter (I would expected to get longer). Please see below my results. Does anyone have any explanation about it or have some hint why this is happening
![figure_1](https://cloud.githubusercontent.com/assets/16032773/12148637/dbea116a-b49f-11e5-9f8b-bc4e2a19355e.png)
?

**Comment by MurphyMc** [comment]
Try running POX with --unthreaded-sh and see if your results are more in line with your expectations.

**Comment by hadik3r** [comment]
Thank you for your response,
The result got better but when I increase the forwarding rate to 70,000 packets per minutes, the pox gives the following error:
ERROR:core:Exception while handling Connection!PacketIn...Traceback (most recent call last):  File "pox/lib/revent/revent.py", line 241, in raiseEventNoErrors    return self.raiseEvent(event, _args, *_kw)  File "pox/lib/revent/revent.py", line 291, in raiseEvent    rv = event._invoke(handler, _args, *_kw)  File "pox/lib/revent/revent.py", line 166, in _invoke    return handler(self, _args, *_kw)  File "sourcerouting.py", line 153, in _handle_PacketIn    self.routing(packet, packet_in,switch_id,in_port,dst_ip)  File "sourcerouting.py", line 124, in routing    self.insertion(packet_in, route, in_port, dst_ip,packet)  File "sourcerouting.py", line 88, in insertion    self.connection.send(msg)  File "pox/openflow/of_01.py", line 848, in send    data = data.pack()  File "pox/openflow/nicira.py", line 365, in pack    po = ofp_packet_out(data=self.data)NameError: global name 'ofp_packet_out' is not defined
Do you know the reason? 

```
On Wednesday, January 6, 2016 11:18 PM, Murphy <notifications@github.com> wrote:
```

 Try running POX with --unthreaded-sh and see if your results are more in line with your expectations.—

**Comment by MurphyMc** [comment]
Looks like a bug.  It should probably be of.ofp_packet_out (the "of." prefix is missing).

**Comment by hadik3r** [comment]
Thank you for your response. 
Actually, I still have some problems with my figure. Although the result got better, the setup time is still decreasing. I tried to profile Pox using cProfile, but I couldn't find any significant changes in different rates. 

I was wondering if there is any explanation for that. 

```
On Tuesday, January 12, 2016 11:13 PM, Murphy <notifications@github.com> wrote:
```

 Looks like a bug. It should probably be of.ofp_packet_out (the "of." prefix is missing).—
