### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Sumairah92** [noxrepo/pox#164]
I am trying to set up a simple topology and running the following command
`./pox.py log.level --DEBUG openflow.discovery openflow.spanning_tree --no-flood --hold-down forwarding.l2_learning`

 But i keep getting the following error

```
DEBUG:openflow.spanning_tree:Requested switch features for [56-ec-57-48-d7-4b 4]
DEBUG:openflow.spanning_tree:Requested switch features for [46-a1-80-c7-55-43 2]
ERROR:openflow.of_01:Exception reading connection [None 5]
Traceback (most recent call last):
  File "/users/sumairas/pox/pox/openflow/of_01.py", line 912, in run
    if con.read() is False:
  File "/users/sumairas/pox/pox/openflow/of_01.py", line 751, in read
    new_offset,msg = unpackers[ofp_type](self.buf, offset)
  File "/users/sumairas/pox/pox/openflow/libopenflow_01.py", line 196, in unpack_new
    r,length = o.unpack(raw, offset)
  File "/users/sumairas/pox/pox/openflow/libopenflow_01.py", line 2160, in unpack
    offset = p.unpack(raw, offset)
  File "/users/sumairas/pox/pox/openflow/libopenflow_01.py", line 722, in unpack
    offset,self.name = _readzs(raw, offset, OFP_MAX_PORT_NAME_LEN)
  File "/users/sumairas/pox/pox/openflow/libopenflow_01.py", line 126, in _readzs
    assert True if (len(d) == 1) else (len(d[1].replace("\x00", "")) == 0)
AssertionError
INFO:openflow.of_01:[None 5] closed
```

Can anyone help regarding this? Thanks

**Comment by MurphyMc** [comment]
What kind of switch are you using?

What's happening here appears to be that the switch is sending a port name which includes a null character in it.  Is it really supposed to contain a null character?  Or is what's after the null garbage?  It's kind of hard to say.

This assertion checks that the field is not just null-terminated, but null-padded, with the assumption that all other cases are degenerate.

If your switch is just including garbage after the proper interface name, you could get away with just commenting this assertion out.  For various other cases (including that parsing is just failing wildly for some reason), this will not help.

**Comment by Sumairah92** [comment]
Thanks for your reply. I am using OVS nodes on GENI portal. The issue seems to be fixed when i checked out the dart branch instead of carp.
