### ISSUE TITLE
misc.gephi_topo: Connection reset by peer

### ISSUE THREAD

**Issue by int331f** [noxrepo/pox#168]
I've started POX with:

```
./pox/pox.py forwarding.l2_learning openflow.discovery misc.gephi_topo openflow.spanning_tree --no-flood --hold-down host_tracker info.packet_dump samples.pretty_log log.level --DEBUG
```

When I run Gephi (0.9.1) and connect to `http://localhost:8282` (stream type: `JSON`) using the Streaming plugin, I get the following error:

```
[misc.gephi_topo        ] Client connect
[lib.ioworker           ] Socket <GephiWorker> error 104 during recv: Connection reset by peer
[misc.gephi_topo        ] Client disconnect
```

**Comment by MurphyMc** [comment]
Which version of POX are you using?  dart has some noteworthy improvements to gephi_topo.

**Comment by MurphyMc** [comment]
Closing as inactive / assuming this was from using the carp version of gephi_topo.

Feel free to reopen.
