### ISSUE TITLE
POX path installation 

### ISSUE THREAD

**Issue by Ali00** [noxrepo/pox#170]
How the POX controller installs the end-to-end paths flow entries (rules)? Is it in parallel or sequential ??

**Comment by MurphyMc** [comment]
I assume you're asking whether POX sends out a bunch of flow mods as quickly as possible (parallel), or whether it sends one out at a time followed by a barrier request and waits for the barrier reply before sending the next one (serial).

The answer is that it's up to an individual component.

**Comment by Ali00** [comment]
Thank you for your replay.

What do you mean by the "individual component ?", is it the forwarding module like (e.g. forwarding.l2_learning).

Reagards,

**Comment by MurphyMc** [comment]
Right.

**Comment by Ali00** [comment]
Many thanks.
