### ISSUE TITLE
controller access APs information and send them orders

### ISSUE THREAD

**Issue by Maryam-Maya-Karimi** [noxrepo/pox#172]
Dear Sir,
I am working on using pox in wireless networks and I need to know the power, packet rate, packet size, location and other information about access points. Is it possible? how can I receive those information in the controller?
and is there any way to send command to the APs to change those variables?

Thank you very much

**Comment by MurphyMc** [comment]
It's outside the scope of OpenFlow and really depends on the device.

I believe there was some work with POX and wireless at Stanford which I believe made a bunch of wireless info available by JSON which could then be retrieved (and edited?) using POX's messenger component, but I couldn't easily find a link.  (And it undoubtedly made assumptions about the particular hardware / system configuration.)

I think this wouldn't be too hard to recreate if your access points run an OS capable of running POX.  You'd run a POX "agent" on the device, which would get/set wireless info via whatever method works for the system configuration and hardware.  Add an interface to it via POX's messenger, and have the agent connect to the controller through its own TCP connection (in addition to the OpenFlow connecion).  (Of course, there's no reason why you'd _need_ to use POX to write the agent.)

If the device already exports an interface to its wireless stuff (e.g., via HTTP), you could also just consume that.
