### ISSUE TITLE
Openflow Queue Stats Reply Nonexisting Parameters 

### ISSUE THREAD

**Issue by balotr** [noxrepo/pox#179]
Hi to all

I am requesting all of the queue stats for a switch like the following function:

    def QueueStatsRequest(event):

        #stats request sender function of switch
        sr = of.ofp_stats_request()
        sr.body = of.ofp_queue_stats_request()
        sr.body.port_no = of.OFPP_ALL
        sr.body.queue_id = of.OFPQ_ALL
        event.connection.send(sr)

Here is the event handler for queue stats:

 
    def _handle_QueueStatsReceived (event):

        #event handler of statistics receive
        #'print's will be updated with logger functions in later versions

        sw = 's%s'%event.dpid
        print "QueueStatsReceived"
        for e in event.stats:
           print "Port no:%s"%str(e.port_no)
           print "Queue id:%s"%str(e.queue_id)
           print "Tx bytes:%s"%str(e.tx_bytes)
        
This gives me the following error:
QueueStatsReceived
ERROR:core:Exception while handling Connection!QueueStatsReceived...
Traceback (most recent call last):
  File "/home/mininet/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/mininet/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/mininet/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/mininet/pox/ext/module_20170320.py", line 73, in _handle_QueueStatsReceived
    print "Port no:%s"%str(event.stats.port_no)
AttributeError: 'list' object has no attribute 'port_no'

if I change my receive function as follows:

 
    def _handle_QueueStatsReceived (event):

        #event handler of statistics receive
        #'print's will be updated with logger functions in later versions

        sw = 's%s'%event.dpid
        print "QueueStatsReceived"
        print (str(event.stats))
        #print "Port no:%s"%str(event.stats.port_no)
        #print "Queue id:%s"%str(event.stats.queue_id)
        #print "Tx bytes:%s"%str(event.stats.tx_bytes)
        #print "check:%d"%event.stats.port_no

what I see is the following output:

QueueStatsReceived
[]

I thought this might be because of the reason that in system no queue is configured however in somewhere before requesting statistics in my code I am executing the following line and the result is same

msg.actions.append(of.ofp_action_enqueue(port = self.mac_to_port[packet.dst], queue_id = 3))

Anyone has an idea?

**Comment by balotr** [comment]
Result is same when I add the following line to QueueStatsRequest function before sending request
    
    sr.type = of.OFPST_QUEUE

**Comment by MurphyMc** [comment]
So whether your switch has queues or not is an aspect of the switch that falls outside of OpenFlow.  It sounds like maybe yours doesn't, or at least like they're not configured.  Is that a possibility?

If you're using Open vSwitch, you should look into adding/configuring queues for Open vSwitch.  A decent place to start might be here: http://docs.openvswitch.org/en/latest/faq/qos/

**Comment by MurphyMc** [comment]
As far as I can tell, this was due to the switch not having queues configured, and not a POX issue, so I'm closing this.
