### ISSUE TITLE
how to detect  link down/ host down so as to preform redirection

### ISSUE THREAD

**Issue by jose2007kj** [noxrepo/pox#180]
![capt](https://cloud.githubusercontent.com/assets/10298207/24532550/fc1be30e-15de-11e7-8ace-20296220952c.png)

sir \madam 
i want the controller to detect link/host down automatically.So as to perform redirection of traffic to a working server instead of server that is down. i run the controller using following command `./pox.py openflow.discovery forwarding.l2_learning` Now i get `closed` message in controller only when exiting from mininet topology

**Comment by MurphyMc** [comment]
If hosts going down results in the link going down, then you could respond to the PortStatus events for links attaching to hosts.

The host_tracker component provides an example of an alternate method, which tries to learn hosts and then periodically ARPs them to see if they're still alive.

**Comment by jose2007kj** [comment]
thanks sir @MurphyMc ,will try that

**Comment by jose2007kj** [comment]
sir, @MurphyMc  ,thanks,now i am able to get host expired message in controller , [i have answered this in my question in stackoverflow](http://stackoverflow.com/a/43139732/5706413)
