### ISSUE TITLE
how to ping between hosts under 2 switches,which have no link switch-switch connection

### ISSUE THREAD

**Issue by tessy123** [noxrepo/pox#181]
how to ping between hosts under 2 switches,which have no link switch-switch connection??
switch1(connect to host1) and switch2(connect to host2) are connected to the controller,...
Is it possible to ping between host1 and host2

**Comment by MurphyMc** [comment]
You could write a component that allowed packets to be relayed through a shared controller... the controller would get packet-ins from one switch and resend them as packet-outs through another switch.  But I have a hard time imagining a case where this is desirable.

**Comment by tessy123** [comment]
thankyou MurphyMc..
