### ISSUE TITLE
AttributError: 'arp' object has no attribute dstip

### ISSUE THREAD

**Issue by jose2007kj** [noxrepo/pox#183]
sir,
I am trying to print the dst ip address with help of str(packet.next.dstip).but i am getting the error AttributError: 'arp' object has no attribute dstip. sir where i might be going wrong

**Comment by MurphyMc** [comment]
I think you're assuming that packet.next is an IPv4 packet.  Instead, it's an ARP packet.  Check that it's actually IPv4.

See [the section about working with packets](https://openflow.stanford.edu/display/ONL/POX+Wiki#POXWiki-Workingwithpackets%3Apox.lib.packet) in the POX manual.

**Comment by jose2007kj** [comment]
ok sir thankyou.......i will check

**Comment by jose2007kj** [comment]
sir,packet is generated when doing ping , sir is it possible to get the ip address from arp packet

**Comment by MurphyMc** [comment]
Well, if the ARP cache doesn't have the destination in it, then a ping will generate an ARP first.

In an ARP packet, the field you're interested in is `.protodst`, which you can see by looking at the [source for the ARP class](https://github.com/noxrepo/pox/blob/carp/pox/lib/packet/arp.py#L81).  There are also examples of this being used in POX.  For instance, the [arp_helper component.
](https://github.com/noxrepo/pox/blob/carp/pox/proto/arp_helper.py#L189)

**Comment by jose2007kj** [comment]
thank you sir and also thanks  for quick help....




``
