### ISSUE TITLE
How to get all host information from Pox controller

### ISSUE THREAD

**Issue by engbarakat** [noxrepo/pox#186]
Hallo,

Im using pox events system to discover the topology and was able so far to detect most of the network. 

I still need to know the ID and port of Hosts that connected to the network, what event or module could help me?

I tried host tracker but I get only switch port and mac/IP of the host

**Comment by MurphyMc** [comment]
The HostEvents of host_tracker have a .new_dpid property.  Isn't that what you want?

**Comment by engbarakat** [comment]
Hi, 

after thinking, I found myself not interested to know the host port. I was able to get the IP and MAC address.

but for sake of discussion, is .new_dpid is the new switch for the moving host?

**Comment by MurphyMc** [comment]
I think it should be...

**Comment by MurphyMc** [comment]
Seems like this issue can be closed.
