### ISSUE TITLE
Adding flow in pox

### ISSUE THREAD

**Issue by humikahout** [noxrepo/pox#189]
How i find output port of custom  topology

**Comment by MurphyMc** [comment]
Well, you could use the discovery component or something like it to discover the links in the topology.  But if you're making your own custom topology, you should know (or be able to figure out) the ports.

**Comment by humikahout** [comment]
I know the output port and also write flows according to my custom topology for all shortest path but its not working in pox 
Can u post ur email address i will send my code and pox file 
Its my project only flow are left i am not abel to add flow.
Thanks

**Comment by MurphyMc** [comment]
Have you tried to create a minimal example?  Like a topology with one switch and three hosts, and a simple controller that statically installs the correct flows?

**Comment by humikahout** [comment]
I am using my own custom topology and also using bellmanford algorithm in pox for all shortest path know i have to add the flow for all possible shortest path

**Comment by MurphyMc** [comment]
The POX manual has [an example of installing table entires.](https://openflow.stanford.edu/display/ONL/POX+Wiki#POXWiki-Example%3AInstallingatableentry).  And POX has a number of examples of doing it (e.g., in the forwarding directory).
