### ISSUE TITLE
Admin access for core developers

### ISSUE THREAD

**Issue by colin-scott** [noxrepo/pox#19]
It looks like Andi, Kyriakos, and I don't have admin status on the repositories. This is problematic when someone needs write access to the repo, but Murphy is not around. Could someone add us as admins?

Thanks!
-Colin

**Comment by MurphyMc** [comment]
(As context, Colin and I talked some about this offline.)

Unfortunately, I can't currently add anyone as admins.  Administrative contacts are me an Amin (though I still need to get Amin more up to speed).

Possible switch of the NOXRepo account to an "organization" in the future, but I suggest further discussion goes to email.
