### ISSUE TITLE
limiting data-rate using pox controller and openflow preventing link congestion

### ISSUE THREAD

**Issue by radwadaadii** [noxrepo/pox#193]
Hi ,

I'm using pox controller and mininet , I need to decrease the data-rate for certain traffic I searched the internet and found the queue method but when limiting the bandwidth using queues created using ovs-vsctl the link is still congested , for example if the host is sending traffic with rate 8 mbps and the rate is limited to 1 mbps , the rate is successfully decreased for the host but the link is still congested as if traffic rate is 8 mbps , is that true or the problem is with my implementation ?

so decreasing the data-rate had no difference on the link and other hosts sharing the same link , is there another way to decrease the data-rate preventing congestion so that other hosts can share the bandwidth

Thanks in advance ,

**Comment by MurphyMc** [comment]
You say the rate is reduced, but it doesn't stop congestion.  How do you know the rate is reduced?  And how do you know there is congestion?

Are you using Mininet to set the links to have a specific maximum bandwidth?  If so, I believe there may be an issue... I think that Mininet uses Linux queue stuff (e.g., netem) to do this.  And queues configured with OVS also use Linux queue stuff.  I'm not sure the two play well together.

There are other factors that also play into whether your experiment will get the expected results.  Mininet is, after all, not a simulator.
