### ISSUE TITLE
Seeing the topology discovered by POX

### ISSUE THREAD

**Issue by SHZ18** [noxrepo/pox#194]
How can I see the topology discovered by POX when it is running?

**Comment by MurphyMc** [comment]
If you mean visually see it... off the top of my head, there's POXDesk (a web UI for POX) or the misc.gephi_topo component.  See [this](https://github.com/MurphyMc/poxdesk/wiki/Getting-Started) and [this](https://openflow.stanford.edu/display/ONL/POX+Wiki#POXWiki-misc.gephi_topo) and the docstrings in the code for more.

**Comment by MurphyMc** [comment]
There's a new and simple way to do this in fangtooth: MurphyMc/pox@5216d18641aee8ecd3f9f314d1adcd49cf78b3e5
