### ISSUE TITLE
How to define multiple ports on POX?

### ISSUE THREAD

**Issue by SHZ18** [noxrepo/pox#195]
I want to connect several switches directly to the pox controller through wired links (in simulation). In this case, should I define multiple interfaces with different listening ports on pox?
How many ports can I define on POX in general?

**Comment by MurphyMc** [comment]
You can probably do this by launching the openflow.of_01 task multiple times.  There shouldn't be any hard limit on how many times you do that.

But for the use case you describe, I don't think there's any need to.  By default it binds to 0.0.0.0:6633, so it should be able to accept connections from all reachable switches.
