### ISSUE TITLE
routing protocol running on top of the POX

### ISSUE THREAD

**Issue by SHZ18** [noxrepo/pox#198]
Hi,

As we know, SDN controllers collects the information to create the topology of the network, after that, based on for example shortest path algorithm, installs the new flow rules on forwarding elements.
Could you let me know which kind of routing protocol or algorithm is running on top of POX to decide how to define flow rules?

**Comment by MurphyMc** [comment]
It depends on the component.  Some of the example components rely on the creation of a spanning tree.  Others use Floyd-Warshall to find paths.  The forthcoming fangtooth branch will probably have a RIPv2 distance-vector implementation and a destination-based forwarding component that uses the Dijkstra's algorithm from NetworkX.

(But I'd probably say that this type of routing isn't really a strength of OpenFlow, and you're often better off creating a fabric using a classic distributed protocol to build a fabric and using OpenFlow to configure the network edges.)

**Comment by MurphyMc** [comment]
Since this is idle, I'm going to close it.

Though for future readers, I'll point out that the fangtooth branch contains an implementation of a traditional routing protocol (RIP) atop OpenFlow.
