### ISSUE TITLE
Betta: Module not found: info.packet_dump

### ISSUE THREAD

**Issue by wuming79** [noxrepo/pox#199]
I'm trying this command below

$ sudo ~/pox/pox.py forwarding.l2_learning \
  openflow.spanning_tree --no-flood --hold-down \
  log.level --DEBUG samples.pretty_log \
  openflow.discovery host_tracker \
  info.packet_dump    

I encounter the following message
Module not found: info.packet_dump.

I'm running betta. Is something missng?

**Comment by MurphyMc** [comment]
In betta, I think it was misc.packet_dump.

Also, if you're just running stock components and you're just starting now... I'd really suggest you run eel.
