### ISSUE TITLE
extensiveness of gitignore

### ISSUE THREAD

**Issue by samwhitlock** [noxrepo/pox#2]
Should the gitignore cover non-pox specific stuff? e.g. I just added the full rule to ignore vim swap files, but should emacs stuff be ignored there too? (just the simple #*# and *~ files it generates)

**Comment by MurphyMc** [comment]
I vote yes.
Education is one of our target audiences, and many users in this category are not likely to have good global settings.  And I'd say we're pretty much never going to have files with wacky timefile names in the repo on purpose. :)

**Comment by samwhitlock** [comment]
I just added the basic emacs ignore files (the ones I mentioned above).

Are there any other files that should be added to the gitignore file? Another common one I see is .DS_Store files for mac users often get added accidentally (e.g. carelessly), but I don't often see them added to gitignore files.

**Comment by MurphyMc** [comment]
I think we have all dotfiles in there already, don't we?

**Comment by samwhitlock** [comment]
Oh I didn't see that. My bad!

I'll revert the redundant vim swapfile rule I made.
