### ISSUE TITLE
pox wiki documentation installation issue

### ISSUE THREAD

**Issue by ghost** [noxrepo/pox#203]
hi,
actually, i'm new in pox and I want to learn how to write a pox application. but the issue is I can't find the pox wiki documentation. I have tried to install from git it installed but there is nothing in the index.html file. could anybody guide me please how I can get the documentation of pox. thanks

**Comment by MurphyMc** [comment]
Unfortunately, the website that hosted the POX wiki has been taken down.

Fortunately, you can still access [an archived version of it](https://web.archive.org/web/20160423221312/https://openflow.stanford.edu/display/ONL/POX+Wiki).

I'll be uploading a new version of it at some point in the hopefully not-too-distant future.

**Comment by ghost** [comment]
thanks 😊


Thanks,

Syed Umer Bukhari (吴马)

E-mail:: umershah81@hotmail.com

Phone:: (92) 150-4414-0645



________________________________
