### ISSUE TITLE
Relaying ICMP packets through the Controller

### ISSUE THREAD

**Issue by AksharPrasanna** [noxrepo/pox#205]
Hello,
I hope this place is right to clarify queries regarding POX usage (tried pox-dev mailing list, but no response).

I have the following topology - 
_H1_-----**S1**----------**S2**----------**S3**----------**S4**-----_H2_

H1 connected to Switch S1
H2 connected to Switch S2

I want to transmit a packet from H1 to H2 without installing flows on S2 or S3. Theoretically therefore, the controller will be transmitting packets directly on to the destination switch without installing any flows on intermediate switches. I am using l2_pairs and full_payload components along with the POX (eel) controller.
I thought of the following implementation methodology -
```
msg = of.ofp_flowmod()
msg.match.dl_dst = packet.src
msg.match.dl_src = packet.dst
msg.actions.append(of.ofp_action_output (port = event.port))
event.connection.send(msg)

msg = of.ofp_flow_mod()
msg.data = event.ofp
msg.match.dl_src = packet.src
msg.match.dl_dst = packet.dst
msg.actions.append(of.ofp_action_output(port = of.OFPP_CONTROLLER))

msg = of.ofp_packet_out(data = event.ofp)
core.openflow.sendToDPID(dst_dpid,msg)

```

dst_dpid refers to the DPID of the destination switch where I want to transmit the packets directly. I am maintaining a table with MAC addresses and the DPIDs of the switches they are connected.

Please let me know if something life this is feasible i.e. if the controller can directly take up the responsibility of relaying the packets to the destination switches without having to install flow rules on the intermediate switches or transmitting the packets through intermediate switches. 

If I do send a packet from H1 to H2, will I face any issues in creating a reverse path for the packet to reach H1 again using the above code.

Any sort of help is appreciated. @MurphyMc 

With Regards
Akshar

**Comment by MurphyMc** [comment]
This seems like a strange thing to do, but yes, it should be possible.  Your flow-mods don't look right to me, though.

If it's just for ICMP packets and you want to do it for all ICMP packets, I'd just install table entries on each switch that send all ICMP packets to the controller.  They don't need to match src or dst at all unless you want them to.  When the controller gets an ICMP packet, figure out where you want it to go and send it to the "last hop" switch as a packet-out.  If you really didn't want to install any table entries, you could skip the first part and rely on the table-miss-sends-to-controller property of OpenFlow 1.0 (as long as you set full payloads as you mention).  In that case all you'd have is a packet-in handler that sends a packet-out when it gets an ICMP message.

In the real world, this doesn't seem like a particularly good design, though.  For example, an attacker could just generate a bunch of ICMP packets and potentially jam up the OpenFlow control connection and/or the controller.  A more robust solution probably entails having a separate offload box to handle ICMP traffic.  But if it's just for an experiment, sure.

**Comment by AksharPrasanna** [comment]
Thanks a ton Murphy! And yes, this is for experimentation.
I will try it out what you said. But I want to clarify some points - 

- When I use the ping command (I use _fping_ to generate packets continuously), based on your suggestion the packet reaches the last hop. But, there is no rule installed on the last switch as to how the packet must be handled. Please correct me if I am wrong, but the packet will not reach the destination host right ? Therefore, I thought of installing rules based on matching `dl_src` and `dl_dst` to output the packet out of  `event.port`. I was partially successful when I tried this before. As in, the reply message could not reach the source host. 

- Considering the table-miss property of OpenFlow, maybe I can modify the code in the following way -
```
table[(event.dpid, packet.src)] = event.port
table_dpid[packet.src] = event.dpid

dst_dpid = table_dpid.get(packet.dst)
dst_port = table.get((dst_dpid, packet.dst))

msg = of.ofp_flowmod()
msg.match.dl_dst = packet.src
msg.match.dl_src = packet.dst
msg.actions.append(of.ofp_action_output (port = event.port))
event.connection.send(msg)

msg = of.ofp_flow_mod()
msg.data = event.ofp
msg.match.dl_src = packet.src
msg.match.dl_dst = packet.dst
msg.actions.append(of.ofp_action_output(port = dst_port))
core.openflow.sendToDPID(dst_dpid,msg)

msg = of.ofp_packet_out(data = event.ofp)
core.openflow.sendToDPID(dst_dpid,msg)
```
I know I am trying to complicate a simple method, but I just want to try out this mechanism. 

- When you say, checking if the packet type is ICMP, is it something like,
`if packet.type is ICMP` 
Is there any particular syntax to follow to check for Packet Type ?

Thanks in Advance

**Comment by AksharPrasanna** [comment]
Hello @MurphyMc ,
Could you please help me with the following error -
```
ERROR:openflow.of_01:[00-00-00-00-00-04 1] OpenFlow Error:
[00-00-00-00-00-04 1] Error: header: 
[00-00-00-00-00-04 1] Error:   version: 1
[00-00-00-00-00-04 1] Error:   type:    1 (OFPT_ERROR)
[00-00-00-00-00-04 1] Error:   length:  36
[00-00-00-00-00-04 1] Error:   xid:     265
[00-00-00-00-00-04 1] Error: type: OFPET_BAD_REQUEST (1)
[00-00-00-00-00-04 1] Error: code: OFPBRC_BUFFER_UNKNOWN (8)
[00-00-00-00-00-04 1] Error: datalen: 24
[00-00-00-00-00-04 1] Error: 0000: 01 0d 00 18 00 00 01 09  00 00 01 22 00 01 00 08   |..........."....|
[00-00-00-00-00-04 1] Error: 0010: 00 00 00 08 00 01 00 00                            |........        |
DEBUG:forwarding.l2_pairs:Installing flow on source 00-00-00-00-00-01
ERROR:openflow.of_01:[00-00-00-00-00-04 1] OpenFlow Error:
[00-00-00-00-00-04 1] Error: header: 
[00-00-00-00-00-04 1] Error:   version: 1
[00-00-00-00-00-04 1] Error:   type:    1 (OFPT_ERROR)
[00-00-00-00-00-04 1] Error:   length:  36
[00-00-00-00-00-04 1] Error:   xid:     267
[00-00-00-00-00-04 1] Error: type: OFPET_BAD_REQUEST (1)
[00-00-00-00-00-04 1] Error: code: OFPBRC_BUFFER_UNKNOWN (8)
[00-00-00-00-00-04 1] Error: datalen: 24
[00-00-00-00-00-04 1] Error: 0000: 01 0d 00 18 00 00 01 0b  00 00 01 23 00 01 00 08   |...........#....|
[00-00-00-00-00-04 1] Error: 0010: 00 00 00 08 00 01 00 00                            |........        |
DEBUG:forwarding.l2_pairs:Installing flow on source 00-00-00-00-00-01
ERROR:openflow.of_01:[00-00-00-00-00-04 1] OpenFlow Error:
[00-00-00-00-00-04 1] Error: header: 
[00-00-00-00-00-04 1] Error:   version: 1
[00-00-00-00-00-04 1] Error:   type:    1 (OFPT_ERROR)
[00-00-00-00-00-04 1] Error:   length:  36
[00-00-00-00-00-04 1] Error:   xid:     269
[00-00-00-00-00-04 1] Error: type: OFPET_BAD_REQUEST (1)
[00-00-00-00-00-04 1] Error: code: OFPBRC_BUFFER_UNKNOWN (8)
[00-00-00-00-00-04 1] Error: datalen: 24
[00-00-00-00-00-04 1] Error: 0000: 01 0d 00 18 00 00 01 0d  00 00 01 24 00 01 00 08   |...........$....|
[00-00-00-00-00-04 1] Error: 0010: 00 00 00 08 00 01 00 00                            |........        |
DEBUG:forwarding.l2_pairs:Installing flow on source 00-00-00-00-00-01
```
I am facing this issue when the following part is executed - 
```
msg = of.ofp_packet_out(data = event.ofp)
msg.actions.append(of.ofp_action_output(port = dest_port))
core.openflow.sendToDPID(dst_dpid,msg)
```
Initially, I thought it was due to payload of the packet being missing. But I am running the `full_payload` component as well.

**Comment by MurphyMc** [comment]
If you send a switch a packet-out with an output action, you don't need to also have a table entry.  You don't need to send either of those flow-mods for this to work.  For the sake of an initial test, I'd suggest you not send any flow-mods at all.

To check if the packet in a POX packet-in handler contains ICMP, the easiest way is to see if .find("icmp") returns something besides None.
