### ISSUE TITLE
Receive error when try to connect POX using custom topolgy in mininet 

### ISSUE THREAD

**Issue by BabakMemar** [noxrepo/pox#208]
I have created a custom topology as following and run it using mininet and connect to POX remote controller.

```
class CustomTopo (Topo):   
    def build(self):
        S1 = self.addSwitch('s1')
        H1 = self.addHost('h1')
        H2 = self.addHost('h2')
        self.addLink(S1, H1)
        self.addLink(S1, H2)

topo = CustomTopo()
net = Mininet(topo)
net.start()
topos = {'mytopo': CustomTopo}
```
It worked correctly first time, but after that I received following error in POX controller when it tried to add links:

**Caught exception. Cleaning up...
Exception: Error creating interface pair (s1-eth1,h1-eth0): RTNETLINK answers: File exists**
 
What can I do to solve it?

**Comment by MurphyMc** [comment]
That doesn't look like a POX error.  Maybe that's a Mininet error?

**Comment by BabakMemar** [comment]
Thank you dear Murphy
You are right, it seems that this problem relates to mininet.
