### ISSUE TITLE
OFPBRC_BUFFER_UNKNOWN Error while collecting packet information and storing it, using pandas.

### ISSUE THREAD

**Issue by adityaprakash-bobby** [noxrepo/pox#210]
I am trying to incorporate a method with the l3_learning module to collect packet count from various IPs in POX network using pandas. The traffic is generated using scapy module and traffic is deployed on network created using mininet. I use POX eel version with PyPy interpreter, but still it shows the OFPBRC_BUFFER_UNKOWN error. What could possibly be wrong?

**Comment by MurphyMc** [comment]
Does the component you're using to set up the tables rely on packet-ins being sent to the controller?  If so, I'd suggest using a different type of forwarding component that doesn't (that is, something more proactive).

**Comment by adityaprakash-bobby** [comment]
@MurphyMc Yes. It depends on the packet-ins. More precisely I want to capture only ipv4 type packets.

**Comment by MurphyMc** [comment]
If you're trying to count packets and have installed a table entry that forwards the packets you're interested in to the controller so that the controller can count them, perhaps a more efficient way would be to just install table entries to match your criteria and forward the packets as normal.  Then you can query the flow stats periodically to actually get the count of packets.

If that's not helpful, maybe you could describe in more detail exactly how this is supposed to be working and what it's supposed to be doing.

**Comment by adityaprakash-bobby** [comment]
Well I am trying to mimic a DDoS in a POX network and have the statistics stored in a separate table. The traffic I am sending is such that each and every packet that comes to the switch is forwarded to the controller. Now my module does that it only reads the packets that have ipv4 header on it and it uses the source IP as attribute to distinguish other packets and increments their count. It has nothing yet to do with the flow table entry. I am just extracting the source IP of packets from each packet-in.

**Comment by MurphyMc** [comment]
If the point of a DDoS is to overwhelm some server (or set of servers), then this design seems to just turn the DDoS into a DDoS against your DDoS measurement system.  Even if the controller were really fast, this means all the traffic from all switches now need to be OpenFlow encapsulated and sent over TCP.  I'd say this design will not hold up.

If you want to be able to keep up with the amount of traffic in a DDoS, I think you probably need to write something in an environment meant for fast packet processing, and it may even need to be distributed (depending on how much traffic there is).  Something like DPDK is probably a better fit than OpenFlow.

**Comment by adityaprakash-bobby** [comment]
Okay. Let me check DPDK and I will get back.
