### ISSUE TITLE
Enable Switch functions to get buffered packets , controller commands  ,timestamps of packet processing

### ISSUE THREAD

**Issue by SyedMohsan** [noxrepo/pox#212]
Sir  @MurphyMc  !
I am unable to extract timestamps of packet when its receive at a switch physical port , command from controller receive at switch , number of packets a switch at a time instance received by switch port, Whereas multiple clients are sending UDP traffic over multiple paths to gateway in my application  .Switch functions are written in switch.py (SoftwareSwitchBase) , but i am unable to get these time instance. How can i enable the switch functions to see what an OVSwitch has buffered while its a part of forwarding path ,or to dump the time statistics in file. mainly i want to explore _rx_flow_mod ,_rx_packet_out ,rx_packet methods. I can process a PacketIn packet easily but additional wanna see inside a switch processing for subsequent packets of a flow additionally. 
regards

**Comment by MurphyMc** [comment]
If I'm understanding correctly, the news isn't good -- those aren't things which are exposed by OpenFlow (or, at the very least, not by the versions of OpenFlow supported by POX).

SoftwareSwitchBase is a software OpenFlow switch implemented in Python.  It's meant for experimentation, debugging, education, etc.  It's not meant for any degree of actual packet forwarding like Open vSwitch is.  If you're using Open vSwitch, the stuff in SoftwareSwitchBase doesn't come into play at all.

**Comment by SyedMohsan** [comment]
sir!
is there support to extract defined parameters for Open VSwitch  in pox 1.0? .Thanks for highlight the module and method of pox python scripts. specifically i need the number of buffered subsequent packet by an Open V Switch [default switch in mininet topology ]and their arrival time at physical port. I am unable to understand how this could be materialize. anticipated thanks for guidelines.

**Comment by geokal** [comment]
Hi @SyedMohsan  maybe you can take some ideas from the below implementation!
[http://csie.nqu.edu.tw/smallko/sdn/latency.htm](url) which creates a packet with the timestamp added.
