### ISSUE TITLE
Exception when running ip_loadbalancer

### ISSUE THREAD

**Issue by josefhammer** [noxrepo/pox#214]
Hi,

I'm trying to run POX with misc.ip_loadbalancer, but I always get the following exception. Any hints on how to solve this?

Thanks a lot!

[mininet@mininet-vm] ~ > sudo ~/pox/pox.py misc.ip_loadbalancer --ip=10.2.0.1 --servers=10.1.0.1,10.1.0.2 info.packet_dump samples.pretty_log log.level --DEBUG
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
INFO:info.packet_dump:Packet dumper running
[core                   ] POX 0.2.0 (carp) going up...
[core                   ] Running on CPython (2.7.6/Oct 26 2016 20:30:19)
[core                   ] Platform is Linux-4.2.0-27-generic-x86_64-with-Ubuntu-14.04-trusty
[core                   ] POX 0.2.0 (carp) is up.
[openflow.of_01         ] Listening on 0.0.0.0:6633
[openflow.of_01         ] [00-00-00-00-00-01 1] connected
[iplb                   ] IP Load Balancer Ready.
[iplb                   ] Load Balancing on [00-00-00-00-00-01 1]
[openflow.of_01         ] [00-00-00-00-00-01 3] connected
[iplb                   ] Load Balancing on [00-00-00-00-00-01 3]
[dump:00-00-00-00-00-01 ] [ethernet][arp]
[core                   ] Exception while handling OpenFlowNexus!PacketIn...

Traceback (most recent call last):
  File "/home/mininet/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/mininet/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/mininet/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/mininet/pox/pox/proto/arp_responder.py", line 189, in _handle_PacketIn
    if _arp_table[a.protosrc] != a.hwsrc:
  File "/home/mininet/pox/pox/proto/arp_responder.py", line 78, in __ne__
    return not self.__eq__(other)
  File "/home/mininet/pox/pox/proto/arp_responder.py", line 76, in __eq__
    return self.mac == other
  File "/home/mininet/pox/pox/lib/addresses.py", line 214, in __cmp__
    return -other.__cmp__(self)
TypeError: bool.__cmp__(x,y) requires y to be a 'bool', not a 'EthAddr'
[openflow.of_01         ] [00-00-00-00-00-02 2] connected
[iplb                   ] Ignoring switch [00-00-00-00-00-02 2]
[dump:00-00-00-00-00-02 ] [ethernet][arp]
[core                   ] Exception while handling OpenFlowNexus!PacketIn...
...

**Comment by MurphyMc** [comment]
Well, POX carp is several years out of date, so the first thing I'd suggest is upgrading and seeing if that helps.

https://noxrepo.github.io/pox-doc/html/#getting-the-code-installing-pox has some notes on versions, etc.  The latest version in the main repo is eel.  You can also try the upcoming fangtooth branch from my fork: https://github.com/MurphyMc/pox

**Comment by josefhammer** [comment]
Thanks a lot! Switching to eel solved the issue! :)
