### ISSUE TITLE
Communicate between two pox controllers?

### ISSUE THREAD

**Issue by raghdaaljaff** [noxrepo/pox#217]
Hello I did two controllers first controller as load balancer and the second controller what act to share information between the C1 and C2 anyone can help me ?

**Comment by raghdaaljaff** [comment]
@MurphyMc

**Comment by VeronicaLiang** [comment]
Hi, I want to do the same thing. Do you have any suggestions to allow multiple controllers to communicate with each other? 

I tried to add one event to core, but controllers couldn't catch it.

**Comment by MurphyMc** [comment]
The final post on #213 may be helpful.
