### ISSUE TITLE
How to use the module?

### ISSUE THREAD

**Issue by raghdaaljaff** [noxrepo/pox#218]
Hello Iam trying to run cpu_loadbalancer-py and cpu_agent.py 
Can somebody show me how I can use  the two above python scripts bcoz I didn’t find any read me document that explain how to apply those python scripts ?

**Comment by raghdaaljaff** [comment]
@MurphyMc

**Comment by raghdaaljaff** [comment]
Any help please?

**Comment by MurphyMc** [comment]
I updated the cpu_loadbalancer gist with a bit of info.  The short short version is this:
1) Download POX.
2) Put cpu_loadbalancer.py and cpu_agent.py in POX's ext/ directory.
3) Follow the directions in the docstring at the top of cpu_loadbalancer.py, which gives the commandlines to use for the controller and for the agents on each server.  You'll have to adapt the cpu_loadbalancer component's commandline to point to the actual servers you want to use.

If you're unfamiliar with running POX at all, you might want to look at the beginning of the manual.

You might run into errors or something if you have the wrong version of POX installed; these little components were written as an example several years ago and aren't maintained.

**Comment by raghdaaljaff** [comment]
Hello everyone I want to apply mahout with pox and mininet,anyone know tutorial or link or blogs I can follow it in this point ,
Thanks everyone 

Regards.
