### ISSUE TITLE
no module found

### ISSUE THREAD

**Issue by AasifRaza98** [noxrepo/pox#223]
folowing error is shown in dispovery.py
"ImportError: No module named pox.lib.revent"

kindly help me in resolving this issue

**Comment by MurphyMc** [comment]
I really can't help without much more context.  Is the problem you're having with completely stock POX, or are you making modifications?  Is there a traceback message?  Which version of POX?

There's a [POX FAQ entry](https://noxrepo.github.io/pox-doc/html/#i-ve-got-a-problem-bug-can-you-help-me) which includes a list of useful things to include when looking for help, such as the commandline you used when the problem occurred.

**Comment by AasifRaza98** [comment]
Thankyou for the reply, my problem is solved.
