### ISSUE TITLE
Virtual Network Slice with POX

### ISSUE THREAD

**Issue by danielbv8** [noxrepo/pox#225]
Hi. I have been practising with a virtual network slice with POX. I mean,  I have to differentiate one type of traffic from another with the help of TCP55 port.

For this i have created two queues, one on which we enqueue traffic we want to pass unrestricted and one on which we enqueue the traffic we want throttled in this way.

sudo ovs-vsctl -- set Port s1-eth1 qos=@newqos -- \
--id=@newqos create QoS type=linux-htb other-config:max-rate=1000000 queues=0=@q0,1=@q1 -- \
--id=@q0 create Queue other-config:min-rate=1000000 other-config:max-rate=1000000 -- \
--id=@q1 create Queue other-config:min-rate=5000 other-config:max-rate=5000

On the other hand i modificated l2_learning.py for managing the traffic with the last indications including in the code something like that.

if msg.match.tp_src == 666 or msg.match.tp_dst == 666:
    msg.actions.append(of.ofp_action_enqueue(port = port,queue_id=1))
else:
    msg.actions.append(of.ofp_action_output(port = port))

In this way i haven´t got any possitive ressults.

What do you think about this? Is the best way for achieve my goal? 
what am I doing wrong? Do you know another thing for to do this?

Thanks in advance

**Comment by danielbv8** [comment]
Someone could help?

**Comment by MurphyMc** [comment]
At first glance, this looks okay, though my ovs-vsctl knowledge is rusty.  Here's some quick thoughts for what they're worth.

You mention "TCP55 port", though the rule seems to be for port 666.  I assume that's not your problem?

I am assuming you have a single switch and that s1-eth1 is indeed the correct (egress) port?

Have you tried dumping the flow table while running and looking at the installed rules?  Do they look correct?

It looks like you may be using this with Mininet.  I no longer use Mininet, but my recollection is that it uses the same mechanism for queuing as OVS does (the queuing configured via `tc`).  It's possible that Mininet is undoing the queue setup you're trying to set up.  Maybe use `tc`, etc. to examine the queue configuration while things are running and make sure it's set up how you think it should be?
