### ISSUE TITLE
ERROR:core:Exception while handling Connection!PacketIn...

### ISSUE THREAD

**Issue by IamBushra** [noxrepo/pox#226]
Hi
When I tried to implement (Path Recovery when link is down) I had an error, I hope to find help.
http://csie.nqu.edu.tw/smallko/sdn/ali.htm

**Thanks..**
```
ERROR:core:Exception while handling Connection!PacketIn...
Traceback (most recent call last):
  File "/home/bushra/pox/pox/lib/revent/revent.py", line 241, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/bushra/pox/pox/lib/revent/revent.py", line 291, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/bushra/pox/pox/lib/revent/revent.py", line 166, in _invoke
    return handler(self, *args, **kw)
  File "/home/bushra/pox/pox/alidijkstra.py", line 111, in _handle_PacketIn
    path = _get_raw_path (mac_map[str(packet.src)][0], mac_map[str(packet.dst)][0])
KeyError: '33:33:00:00:00:02'
_hanle_PacketIn() is called at 10
packet.src= ce:88:44:e3:a1:67  packet.dst= 33:33:00:00:00:16
```

**Comment by MurphyMc** [comment]
'33:33:00:00:00:02' seems to not be in mac_map, but I couldn't really tell you why.  alidijkstra.py isn't a stock POX module -- you would probably have better luck asking the original author.
(alidijkstra.py looks like it was based on POX's l2_multi.py, which doesn't put string versions of addresses in mac_map -- it uses actual EthAddrs.  So I think their modifications must have been pretty extensive.)

**Comment by IamBushra** [comment]
**Thanks a lot for your response**, I'm trying to implement [Using Bellman-Ford to find a shortest path](http://csie.nqu.edu.tw/smallko/sdn/bellmanford.htm). but when run ping between h1 and h2 the packet didn't reach.
```
~/pox$ ./pox.py bellmanford openflow.discovery
POX 0.5.0 (eel) / Copyright 2011-2014 James McCauley, et al.
INFO:core:POX 0.5.0 (eel) is up.
INFO:openflow.of_01:[00-00-00-00-00-01 1] connected
INFO:openflow.of_01:[00-00-00-00-00-05 5] connected
INFO:openflow.of_01:[00-00-00-00-00-04 2] connected
INFO:openflow.of_01:[00-00-00-00-00-03 3] connected
INFO:openflow.of_01:[00-00-00-00-00-02 4] connected
WARNING:bellmanford:Not flooding -- holddown active
INFO:openflow.discovery:link detected: 00-00-00-00-00-01.2 -> 00-00-00-00-00-02.1
INFO:openflow.discovery:link detected: 00-00-00-00-00-01.3 -> 00-00-00-00-00-03.1
INFO:openflow.discovery:link detected: 00-00-00-00-00-05.1 -> 00-00-00-00-00-02.2
INFO:openflow.discovery:link detected: 00-00-00-00-00-05.2 -> 00-00-00-00-00-04.2
INFO:openflow.discovery:link detected: 00-00-00-00-00-04.1 -> 00-00-00-00-00-03.2
WARNING:bellmanford:Not flooding -- holddown active
```

**Comment by YUNISDAHA** [comment]
Hi MurphyMc, and Bushra,

I am also facing the same issue, When I tried to implement (Path Recovery when link is down) I had an error, I hope to find help.
http://csie.nqu.edu.tw/smallko/sdn/ali.htm

ERROR:core:Exception while handling Connection!PacketIn...
Traceback (most recent call last):
  File "/home/bushra/pox/pox/lib/revent/revent.py", line 241, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/bushra/pox/pox/lib/revent/revent.py", line 291, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/bushra/pox/pox/lib/revent/revent.py", line 166, in _invoke
    return handler(self, *args, **kw)
  File "/home/bushra/pox/pox/alidijkstra.py", line 111, in _handle_PacketIn
    path = _get_raw_path (mac_map[str(packet.src)][0], mac_map[str(packet.dst)][0])
KeyError: '33:33:00:00:00:02'
_hanle_PacketIn() is called at 10
packet.src= ce:88:44:e3:a1:67  packet.dst= 33:33:00:00:00:16

I request you If you can you please share your valuable feed back.

looking forward to your kind response,

email ID: dahayounis@gmail.com

**Comment by MurphyMc** [comment]
Since it looks to me like this problem originates in code that doesn't come with POX, I'd suggest contacting the author of that code.

**Comment by YUNISDAHA** [comment]
Thank you Sir, 

I have emailed him, let hope for goodness. 

any suggestion that might help me to overcome this error?

**Comment by MurphyMc** [comment]
Again, I didn't write the code, so I don't necessarily know it any better than you do.

On the other hand, I think the code that generated that stack trace must have been modified from the version posted on the linked website.  Maybe if you posted the version with your modifications, it would be possible to see what's happening.
