### ISSUE TITLE
Factor out deadlock-helper code from pox.py

### ISSUE THREAD

**Issue by MurphyMc** [noxrepo/pox#23]
ed54673 added some code to help find deadlocks.  I don't love this actually living in pox.py.  Could it be moved out to a module in misc or something?  (The I-think-not-entirely-dissimilar recoco_spy is there in misc already.)

**Comment by colin-scott** [comment]
Feel free to move it

**Comment by MurphyMc** [comment]
Thanks.

Done in my repo; it should eventually find its way upstream.
