### ISSUE TITLE
How to use forwarding.l2_multi

### ISSUE THREAD

**Issue by Calocorbo94** [noxrepo/pox#232]
Hi all,
I am newbie in this field and I have some questions about the pox controller when run forwarding.l2_multi.

First of all I would want to know if when I run it in a full meshed topology the network should work and how it should be run.
However, I tried to build a minimal topology typing "sudo mn --controller=remote,ip=127.0.0.1,port=6633", then I run pox controller as follow "sudo ./pox.py openflow.discovery forwarding.l2_multi".
What I see is this: 

INFO:core:POX 0.5.0 (eel) is up.
INFO:openflow.of_01:[00-00-00-00-00-01 1] connected

But when I try to do pingall in mininet, it doesnt' work.
Do you know what am I doing wrong?

**Comment by MurphyMc** [comment]
You'll need to also run the spanning_tree or spanning_forest component in order to remove loops.

**Comment by Calocorbo94** [comment]
Thank you for the fast answer Murphy, but I'm not sure it's the solution.
I try to run also spanning_tree but it does still not work. 
However my network hasn't loop, in fact when I run the command "sudo mn", the network has one switch and two hosts. So I don't think the problem is the spanning tree.

Any other suggestions?

**Comment by Calocorbo94** [comment]
I solved in this way:

 ./pox.py openflow.spanning_tree openflow.discovery forwarding.l2_multi

And the answer to my first question is that forwarding.l2_multi works similar to the forwarding.l2_learning but in a different way (by using the openflow.discovery).

**Comment by MurphyMc** [comment]
Sorry, I hadn't read this closely enough.  In your trivial single switch "full mesh", there are no loops, so you shouldn't need spanning_tree (though it shouldn't really hurt either).

But now I don't see why what you said in the first post didn't work and what you said in your most recent post does...
