### ISSUE TITLE
Messenger has a magic print statement?

### ISSUE THREAD

**Issue by MurphyMc** [noxrepo/pox#24]
279a9ecf6edaf6307fff777d7d6c581ad41acb6c adds back a print statement that reportedly magically fixes a crash.

Can I get a dead-simple test case for this so we can fix it for real?

Or can we somehow address this?

What kind of a crash / failure would we get?  Are there stack traces?

Anything?

Let's try to put this one to bed. :)

**Comment by zarifis** [comment]
Yeah, this baffled me. I couldn't associate the lack of the print statement
to the crash with 100% certainty, but I remember trying to isolate the
problem by commenting out possible offending snippets, and it really came
down to printing the.
Then again, I couldn't always reproduce the crash when the print wasn't
there. And I just tried again now, and I couldn't.

Also, I don't think there was any meaningful stack trace when I saw it, or
any error message for that matter, which made it even more frustrating to
troubleshoot.

So, I don't know, maybe just ignore it. Until I or someone else comes
across it again.

On Sun, Jun 17, 2012 at 11:12 PM, Murphy <
reply@reply.github.com

**Comment by MurphyMc** [comment]
I'm thinking I'm finally going to push my second-generation messenger as part of the summer development cycle, so who knows it might just go away anyway.  At any rate, existing apps -- if we want them to remain -- will need to be at least slightly updated, so we may have another chance to run into the issue as part of doing that.

Can you at least describe the symptom in as good detail as you can remember for the record?  Did it just stop working?  As if sends were no longer going through?  Or... ?

**Comment by zarifis** [comment]
Yes, the messenger would quietly stop working. What I cannot remember is
whether it was the whole messenger or the specific channel. I think it was
the latter.

On Sun, Jun 17, 2012 at 11:53 PM, Murphy <
reply@reply.github.com

**Comment by MurphyMc** [comment]
Just a note that this bug _definitely_ goes away with messenger 2.0 -- because it doesn't have the muxer.  So when that gets pushed, this can be closed.

**Comment by MurphyMc** [comment]
The new code is in the betta branch, so I'm closing this.
