### ISSUE TITLE
AssertionError - assert s1 is not s2 in spanning_tree.py

### ISSUE THREAD

**Issue by trademkose** [noxrepo/pox#243]
Hi,

I have a topology like this;

![resim](https://user-images.githubusercontent.com/7984679/77203744-3c0fda80-6b02-11ea-9347-97830d74826b.png)

			
I start my topology by using this command;
> sudo python testtopo.py

And I have started POX controller with a few modules.
I added the spanning tree module because my topology has a loop.

> sudo /home/mininet/pox/pox.py log.level --CRITICAL forwarding.l2_learning
openflow.discovery --eat-early-packets openflow.spanning_tree --no-flood --hold-down

But I am getting the following error. How can I fix this error?
Could you help me?

Best Regards.

Error:

**### File"/home/mininet/pox/pox/openflow/spanning_tree.py",line 73,
in_calc_spanning_tree
assert s1 is not s2
AssertionError**

**Comment by MurphyMc** [comment]
I'm not sure why this would be.  A couple quick recommendations:
1) If this was a version of POX shipped with Mininet, make sure it's up to date.
2) Try the spanning_forest component instead; it's quite a bit newer (which can be both a good and bad thing)

The official repository is currently lagging way behind mine: https://github.com/MurphyMc/pox

**Comment by trademkose** [comment]
I am getting the same error when I have updated the POX controller from your repository of POX.(https://github.com/MurphyMc/pox.git)

-Trying with spanning_tree;

sudo /home/mininet/Downloads/mypox/pox/pox.py log.level --DEBUG forwarding.l2_learning openflow.discovery --eat-early-packets openflow.spanning_tree --no-flood --hold-down


-Error;

AssertionError
ERROR:core:Exception while handling Discovery!LinkEvent...
Traceback (most recent call last):
  File "/home/mininet/Downloads/mypox/pox/pox/lib/revent/revent.py", line 242, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/mininet/Downloads/mypox/pox/pox/lib/revent/revent.py", line 295, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/mininet/Downloads/mypox/pox/pox/lib/revent/revent.py", line 168, in _invoke
    return handler(self, *args, **kw)
  File "/home/mininet/Downloads/mypox/pox/pox/openflow/spanning_tree.py", line 166, in _handle_LinkEvent
    _update_tree()
  File "/home/mininet/Downloads/mypox/pox/pox/openflow/spanning_tree.py", line 178, in _update_tree
    tree = _calc_spanning_tree()
  File "/home/mininet/Downloads/mypox/pox/pox/openflow/spanning_tree.py", line 73, in _calc_spanning_tree
    assert s1 is not s2
AssertionError

-------------------------------------


-Trying with spanning_forest;

sudo /home/mininet/Downloads/mypox/pox/pox.py log.level --DEBUG forwarding.l2_learning openflow.discovery --eat-early-packets openflow.spanning_forest


Error;

ERROR:core:Exception while handling Discovery!LinkEvent...
Traceback (most recent call last):
  File "/home/mininet/Downloads/mypox/pox/pox/lib/revent/revent.py", line 242, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/mininet/Downloads/mypox/pox/pox/lib/revent/revent.py", line 295, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/mininet/Downloads/mypox/pox/pox/lib/revent/revent.py", line 168, in _invoke
    return handler(self, *args, **kw)
  File "/home/mininet/Downloads/mypox/pox/pox/openflow/spanning_forest.py", line 386, in _handle_openflow_discovery_LinkEvent
    link = self.topo.get_link(e.link)
  File "/home/mininet/Downloads/mypox/pox/pox/openflow/spanning_forest.py", line 323, in get_link
    raise RuntimeError(emsg)


Thanks for your reply.

**Comment by MurphyMc** [comment]
I'm completely guessing here, but I am wondering if your topology isn't quite what you think it is.  Specifically, I'm wondering if it has parallel edges and that's breaking assumptions in the spanning tree and spanning forest components.

**Comment by trademkose** [comment]
@MurphyMc You can see my topology on attached file.
[testtopo.txt](https://github.com/noxrepo/pox/files/4368812/testtopo.txt)

**Comment by MurphyMc** [comment]
The actual error that spanning_forest is raising is: "Dynamic/hubbed/multi-access topology not supported"

.. there's something about your topology that isn't expected.

What happens if you start Mininet, wait a a little while, and then start POX manually a while later?  Any change?

**Comment by trademkose** [comment]
I found my fault on my topology script.
       #h1 host setting
        h1 = net.get( 'h1' )
        h1.intf( 'h1-eth0' ).setIP( '192.168.123.2', 24 )
        h1.intf( 'h1-eth0' ).setMAC( '8:8:8:8:8:8' )

I have set h1 value instead of h2 in this code block by mistake.
        #h2 host setting
        h1 = net.get( 'h2' )
        h1.intf( 'h2-eth0' ).setIP( '192.168.123.3', 24 )
        h1.intf( 'h2-eth0' ).setMAC( '8:8:8:a:a:a' )

H1 should be H2 .
Assertion Error has been occurred due to my fault.
Thanks for your reply. We can close this issue.
