### ISSUE TITLE
Ip balancer with more than one service ips

### ISSUE THREAD

**Issue by spartakos87** [noxrepo/pox#244]
Can you explain to me what exactly this piece of code is done?
https://github.com/noxrepo/pox/blob/412a6adb38cb646748c8cfb657549787ab6d2e88/pox/misc/ip_loadbalancer.py#L336

I want to parse more than one service ip and to handle them inside class iplb, but I do not understand the use of this command

**Comment by MurphyMc** [comment]
This and the block of code above it make the load balancer respond to ARPs, if I remember correctly.
