### ISSUE TITLE
POX issues with the iperf3 UDP protocol

### ISSUE THREAD

**Issue by wkruetzer** [noxrepo/pox#246]
I run my custom mininet topology on a terminal and want to use iperf3

in pox i used this component:
`./pox.py forwarding.l2_learning `

in mininet I used xterm h1 h2
then i use iperf3 with the udp protocol
in h1 xterm:
`iperf3 -s`
in h2 xterm:
`iperf3 -c 10.0.0.1 -u`

when I run iperf with a bandwidth of 1 Mbits / sec, it works fine even though I get high jitter(>20ms)
but when I run iperf with a bandwidth of 10 Mbits/sec or 100 Mbits/sec, I get a large packet loss and sometimes OUT OF ORDER, does this happen because of a POX or Iperf3 error ??

Any sort of help is appreciated. @MurphyMc

```
[  31]   1.00-2.00   sec   489 KBytes  3.51 Mbits/sec  17.150 ms 50/104 (48%)
iperf3: OUT OF ORDER - incoming packet = 85 and received packet = 199 AND SP = 31
iperf3: OUT OF ORDER - incoming packet = 86 and received packet = 199 AND SP = 311
```
in pox terminal :
```
INFO:packet:(udp parse) warning UDP packet data shorter than UDP len: 94 < 231
INFO:packet:(udp parse) warning UDP packet data shorter than UDP len: 94 < 2570
INFO:packet:(udp parse) warning UDP packet data shorter than UDP len: 94 < 23724
INFO:packet:(udp parse) warning UDP packet data shorter than UDP len: 66 < 8200
INFO:packet:(udp parse) warning UDP packet data shorter than UDP len: 66 < 8200
INFO:packet:(udp parse) warning UDP packet data shorter than UDP len: 66 < 8200
INFO:packet:(udp parse) warning UDP packet data shorter than UDP len: 66 < 8200
```

**Comment by MurphyMc** [comment]
Run l2_pairs instead of l2_learning.

**Comment by wkruetzer** [comment]
wow thanks a lot @MurphyMc , now I can finish my homework
