### ISSUE TITLE
how to work with network with loop in connection with pox controller

### ISSUE THREAD

**Issue by pvshalini** [noxrepo/pox#253]
Hi sir
I use mininet with pox controller.
In mininet terminal when I give the command 'sudo mn --topo=torus,3,3 --controller=remote --switch=lxbr,stp=1 '
the pingall is working successfully, but in pox terminal 'connection aborted' is displayed
I want to know how to make the network with loop work (ping) and at the same time connect to the controller
![mininet](https://user-images.githubusercontent.com/36400183/100190346-0edabe00-2f14-11eb-95af-94d0983d658b.png)
![pox](https://user-images.githubusercontent.com/36400183/100190370-1ac68000-2f14-11eb-9472-a29efe3f0812.png)

**Comment by MurphyMc** [comment]
This is a general problem with learning switches.  You'll want to run it with the spanning_tree or spanning_forest component.  (Or write a better routing component.)
