### ISSUE TITLE
pox error

### ISSUE THREAD

**Issue by pvshalini** [noxrepo/pox#255]
sir
I am getting error 
not sending packet for ip address back out of the input port
and
Error: core: Exception while handling Discovery ! LinkEvent....
I am running pox with spanning tree for half mesh topology

![error pox](https://user-images.githubusercontent.com/36400183/101475888-ed95bb00-3972-11eb-8425-7a4040afb323.png)

**Comment by MurphyMc** [comment]
Can you please share your exact topology?

In the meantime, I'd suggest trying the spanning_forest component instead of spanning_tree.

**Comment by pvshalini** [comment]
sir
I am a student pursuing PhD
I am implementing the topology given in the attached picture
Thanks and Regards
Shalini

**Comment by MurphyMc** [comment]
Unfortunately, I don't see any attachment.

But I think that assertion hits when there are self loops in the topology.  The spanning_tree component just doesn't handle that case.

**Comment by pvshalini** [comment]
sir
could you please tell how to implement the topology given in the attached
file ( half-mesh topology)
and could you please tell how to run a proxy controller (1 pox controller,
1 mininet, 1 proxy controller for pox)
Thanks and Regards
Shalini

**Comment by MurphyMc** [comment]
I'm afraid that I still can't see your topology, and I don't know what a proxy controller is.  Sorry I can't be of more help!
