### ISSUE TITLE
Cpu consumption

### ISSUE THREAD

**Issue by lorenzomonta** [noxrepo/pox#257]
How can I view the cpu consumption of the pox controller?

**Comment by MurphyMc** [comment]
Same way you view the CPU consumption of any process, really.  Like "top" on Unix-like systems, or Task Manager on Windows.

**Comment by lorenzomonta** [comment]
What is the name of the process associated with the POX controller?
How I can find the pid of the POX controller process?

@MurphyMc 

Can you help me please?

**Comment by MurphyMc** [comment]
POX is written in Python, so the process name is probably whatever your Python interpreter is called (e.g., `python3`).

I guess you find the PID the same way you find any PID.  If Mininet is running POX, then it seems like Mininet would be in the best position to know.  Or you could use POX's misc.pidfile component to save the PID to a file...?

**Comment by lorenzomonta** [comment]
> POX is written in Python, so the process name is probably whatever your Python interpreter is called (e.g., `python3`).
> 
> I guess you find the PID the same way you find any PID. If Mininet is running POX, then it seems like Mininet would be in the best position to know. Or you could use POX's misc.pidfile component to save the PID to a file...?

Could be "python3 -u /home/mininet/pox/pox.py forwarding.l3_detectionEntropy"?

@MurphyMc

**Comment by MurphyMc** [comment]
Yes, that's certainly POX.

**Comment by lorenzomonta** [comment]
> Yes, that's certainly POX.

Thank you very much!
