### ISSUE TITLE
No module named:pox.boot

### ISSUE THREAD

**Issue by Harleen8-Bagga** [noxrepo/pox#262]
I have already installed pox using python 2.7 in UBUNTU 20.04 then why am I getting this error?

from pox.boot import boot

ImportError:NO module named boot

Please help I have been struggling with this for a very long time.

**Comment by Harleen8-Bagga** [comment]
I have been struggling with it for a very long time please help. I installed pox using "git clone http://github.com/noxrepo/pox".I came to know that pox can't detect python3 which is present in UBUNTU 20.04 by default. I really can't understand what's going wrong please help.

**Comment by MurphyMc** [comment]
The gar-experimental branch of POX, which is the default, actually does use Python 3 (it says so in the README).

However, POX is not normally used like a library that you import.  It's possible, but unusual (I haven't used it this way for years, so far all I know, it's currently broken).  The usual way is to write a POX component, and then run it using POX.  Have you looked at the POX manual?  It discusses this...
https://noxrepo.github.io/pox-doc/html/#invoking-pox
https://noxrepo.github.io/pox-doc/html/#developing-your-own-components

If you actually want to use POX as a library, the first thing you need to do is add the POX directory for your PYTHONPATH.

**Comment by Harleen8-Bagga** [comment]
Yeah, I got it. I have been installing the wrong branch for pox. And I didn't add the library in the PATH as well. Finally, my errors are resolved. I should have read the documentation carefully.
Thanks a lot.
