### ISSUE TITLE
want to install two actions for the flow rule to send packet to destination and also controller

### ISSUE THREAD

**Issue by pvshalini** [noxrepo/pox#267]
sir
I am using mininet with pox controller.
when a packet_in message arrives at a controller, I want a copy of subsequent packets from the source to be sent to the controller as well as destination.
I called function self._send_lost_buffers(dpid, packet.next.srcip, packet.src, OFPP_CONTROLLER)
Kindly see the error message in the screenshot.
Please advice how to get two actions for the flow rule (1) to send copy to destination and (2) to send another copy to the controller.
Thank you sir
![controller flow rule](https://user-images.githubusercontent.com/36400183/128172119-a46a00b8-846e-4c83-b346-7459b03b9b39.png)

**Comment by MurphyMc** [comment]
I don't know if what you're doing and how you're planning to do it is reasonable, but the immediate problem is just that OFPP_CONTROLLER is defined in libopenflow_01, which is imported as "of".  You need to qualify your reference to it, as is done with OFPP_NONE elsewhere in the original l3_learning.py file.  That is, you want to say `of.OFPP_CONTROLLER`.

**Comment by pvshalini** [comment]
Thank you sir
The error is resolved by making OFPP_CONTROLLER as of.OFPP_CONTROLLER,
sir, I am a research scholar working in SDN. I create a network topology using mininet. using xterm opened two hosts terminals, in  host 1 terminal I created a webserver, in host 2 terminal I gave a command curl "http://host1 ipaddress : port number".  
I want to trace final ACK packets of curl command at the controller, for this I modified l3_learning program by adding
(1) "msg.actions.append(of.ofp_action_output(port=of.OFPP_CONTROLLER))" in 
 elif isinstance(packet.next, arp): block in else part
(2) msg.actions.append(of.ofp_action_output(port=of.OFPP_CONTROLLER)) is added to all flow rule installations
The problem is I am getting multiple copies of ACK packet, please suggest how to resolve this
Thank you sir
![error message1](https://user-images.githubusercontent.com/36400183/128398271-390169e0-46b6-415a-907d-bc702661fcae.png)

**Comment by pvshalini** [comment]
Thanks sir
