### ISSUE TITLE
[ERROR when running module of POX]

### ISSUE THREAD

**Issue by vucuong1820** [noxrepo/pox#268]
While I running these codes: **_./pox.py openflow.discovery forwarding.l2_learning openflow.spanning_tree_**
It appears the error messages:

WARNING:version:Support for Python 3 is experimental.
INFO:core:POX 0.7.0 (gar) is up.
ERROR:openflow.of_01:Error 98 while binding 0.0.0.0:6633: Address already in use
ERROR:openflow.of_01: You may have another controller running.
ERROR:openflow.of_01: Use openflow.of_01 --port=<port> to run POX on another port.

**Comment by MurphyMc** [comment]
See #128
