### ISSUE TITLE
Older Version needed

### ISSUE THREAD

**Issue by MoMon3m** [noxrepo/pox#271]
Hi 
I need any old version of Pox that supports python 2 but I can't find any on the internet.
Can you please assist me with that?

**Comment by MurphyMc** [comment]
The `fangtooth` branch is the most recent branch that supports 2.7.  So clone the repo and checkout the fangtooth branch.  The [relevant section of the documentation](https://noxrepo.github.io/pox-doc/html/#selecting-a-branch-version) may help a little.
