### ISSUE TITLE
Values of nw_proto are incorrectly labeled in the comments.

### ISSUE THREAD

**Issue by JoeySo22** [noxrepo/pox#276]
Hello,

In dart, I realized that the comments on /pox/pox/openflow/libopenflow_01.py line 1267 are incorrectly labelling the respective values above it.

Says (1, 6, 17) -> TCP/UDP/ICMP

I discovered with dpctl dump-flows that (1, 6, 17) maps to ICMP/TCP/UDP

**Comment by MurphyMc** [comment]
I don't think it was really meant to imply that 1, 6, 17 corresponded to TCP, UDP, ICMP respectively.  The comment isn't really labeling those things -- it's just describing what it means that it's inside the `if` body.

That said, the [earlier version of this code](https://github.com/noxrepo/pox/blob/a254e58d48aedae6e5531a2393491016465f4dc5/pox/openflow/libopenflow_01.py#L480) (which I wrote) did have them listed respectively.  I've fixed it on the gar branch of my fork.  It'll eventually make its way to the gar branch here.
