### ISSUE TITLE
No access to Internet after running POX  and connected to OpenWRT router 

### ISSUE THREAD

**Issue by EngHassanJ** [noxrepo/pox#283]
Hello 
Dear @MurphyMc 

I have installed POX on ubuntu 20.04  + have installed OVS on the OpenWRT router . . 

I have set the OpenWRT router as an access point,  but when I  run POX and connect the OpenWRT through ovs , I cant access the internet! 

actually, when using this command: "/ usr/share/openvswitch/scripts/ovs-ctl start"  to start listening to pox  , the host they connected to OpenWRT router can't access the internet 

did you know why?. before running pox the router worked fine 

thanks in advanced

**Comment by MurphyMc** [comment]
This is a difficult question to answer more precisely than "it's configured wrong".

You're starting OVS.  Does OVS connect to POX?  (It should show up in the POX logs; make sure to run with the POX logging turned to DEBUG level for testing.)

Also, what configuration are you using for POX?

**Comment by EngHassanJ** [comment]
thank you for response  

> Does OVS connect to POX? 

yes it does 

the pox working fine , but I notice  that: 
1- if the OpenWRT router worked as a wireless repeater, after started the command 
     "/ usr/share/openvswitch/scripts/ovs-ctl start"    >>>  the pox just shows me the main router's logs but not the OpenWRT and also OpenWRT have no access to the internet 

2-  if I connect OpenWRT router to the main router through an Ethernet cable,   hosts can access the internet for some wireless zones but not all zones and the loges of openwrt shows.

show the screenshots:
![Screen Shot 2022-11-18 at 1 06 28 PM](https://user-images.githubusercontent.com/76851714/202677320-7a47adc8-9adc-4f9e-b137-2f96bee6a0a0.png)

StC_2021 : Main Router 

HassanSDN zone :  Main wireless network for openWrt 

the other Zones as shows inside red rectangle  have no access to internet after running the commands :  "/ usr/share/openvswitch/scripts/ovs-ctl start"



the pox logs ; 

![Screen Shot 2022-11-16 at 7 55 10 PM](https://user-images.githubusercontent.com/76851714/202677995-24489ac3-4a53-480b-ad2d-5da818abb473.png)



I'm sorry I know this makes you confusing, but let me know if you need other details.

**Comment by MurphyMc** [comment]
I don't have any idea how OpenWRT's zones work or what the OVS configuration is like, so I am missing some important information.

One thing I'd try is running l2_learning instead of l3_learning.
