### ISSUE TITLE
Can a host in mininet connect to internet or webserver

### ISSUE THREAD

**Issue by pvshalini** [noxrepo/pox#286]
I am working on a project "Detection of outgoing DDoS attack"
I am using mininet with pox-fangtooth controller
![internet from host](https://user-images.githubusercontent.com/36400183/211281163-7c033b4c-5ad4-4b9e-89fe-f6780ebb4ac0.png)
this screenshot is the xterm terminal of host h1
I want the hosts in the mininet network to access an external server or a web server
Could you kindly guide on how to connect host to internet

**Comment by MurphyMc** [comment]
Well, whatever component you're running in POX needs to be able to support it, but that's probably less of an issue than getting the mininet configuration right, which is out of POX's control.
