### ISSUE TITLE
Controller connected to some switches

### ISSUE THREAD

**Issue by TereVenegas** [noxrepo/pox#291]
Hello there! 
I have a question but I'm not sure if it's even possible on pox. I have this topology in mininet

h1      h2      h3
|        |        |
sw1 --- sw2 --- sw3
|
C0

So, my controller is only connected to sw1 but if I wanted to make a ping from h3 to h2, how can I make the controller send the proper forwarding rules to sw3 and sw2 if they are not connected, how can I do that? 
I am feeling so lost in this scenario. 

If anyone could give me some feedback I would really appreciate it!  
thanks.

**Comment by MurphyMc** [comment]
It's certainly possible with POX.

Assuming you're using Open vSwitch, the easy way is by taking advantage of the fact that OVS specifically supports this type of scenario.  The relevant term is "in-band control".  The OVS docs discuss it in at least two places: [Design Decisions](https://docs.openvswitch.org/en/latest/topics/design/) and the [Using OpenFlow FAQ](https://docs.openvswitch.org/en/latest/faq/openflow/).

Actually getting that set up is mostly a matter of configuring OVS/mininet correctly.  As that's outside of POX's scope, I'm going to wish you luck and close this issue. :)
