### ISSUE TITLE
recoco.Sleep doesn't seem to be working 

### ISSUE THREAD

**Issue by nskjellum** [noxrepo/pox#299]
This function is one of the least explained within the Pox library. However, I was optimistic when Lock worked as expected, but found that simply declaring recoco.Sleep(n=timeToWake) did nothing to affect the recoco process at all, and it simply continued executing. I also attempted this with recoco.Sleep(n), but likewise found it to not work. This frustrates my work as I now need to split multiple functions into Timer compatible functions in order to get any work done. Do you have any solutions to what might be causing this?

**Comment by MurphyMc** [comment]
Are you yielding to it?  As with all the recoco `BlockingOperation`s, you need to use it with `yield`.  There's an example of this in [the messenger's tcp_transport](https://github.com/noxrepo/pox/blob/5f82461e01f8822bd7336603b361bff4ffbd2380/pox/messenger/tcp_transport.py#L163).

In short, to sleep for three seconds inside a recoco task, you'd do:
```
yield recoco.Sleep(3)
```

There was some work on recoco which made this sort of error a bit more obvious, I believe, but I'm not sure if it will ever get merged, since I think it's likely that the next major work on recoco will be a pretty substantial rewrite to integrate it with Python 3's asyncio (or at least make use of Python 3's new async / yield semantics).

**Comment by nskjellum** [comment]
Ah, I see. This lines up with the other advice for other blocking operations but seems I was a bit pigheaded to notice those. Thank you very much, I suspect this will work (and also fix my use of locks, which I likewise did not use yield with.)

**Comment by nskjellum** [comment]
Apologies, but I got the chance to try this again, and it still doesn't seem to be working. 

The way I'm using it is to attempt to use it as one would a typical python3 sleep. However, just writing yield recoco.Sleep(N) leads to function issues, as the yield interferes with the return values of my functions. I attempted to remedy this by having the yields be contained in their own functions which themselves call the recoco sleep, but this results in them not functioning at all. 

```


def faux_sleep(time):
    print("We tried to sleep")
    yield recoco.Sleep(timeToWake = time)

def faux_acquire(lock):
    yield lock.acquire()

def faux_release(lock):
    yield lock.release()
```
And here's the call which should be delaying execution by 2 seconds, but does the full loop anyway
```
        for i in range(5):
            faux_sleep(2)
            #yield recoco.Sleep(timeToWake = 2, absoluteTime = False)
```

**Comment by nskjellum** [comment]
Still having issues with this, I've assumed that the yield Sleep argument would function like the typical blocking sleep, but it does not. I think a more intuitive example is required, as the yield structure is not compatible with the way I'm working and I would be forced to used timers as a functional sleep instead, which I'd prefer not to.

**Comment by nskjellum** [comment]
Here is the pertinent code I'm trying to make work, since I use it similarly here and elsewhere. 


```
    def _go_up (self, event):

        def con_check():

            while core.running:

                if len(self.connections) < 8:
                    log.info("Still waiting on those connections sir.")
                    #time.sleep(1)
                    #yield recoco.Sleep(1)
                    #faux_sleep(1)
                else:
                    log.info("We have established our connections!")
                    break

            log.info("We have our connections!")
            log.info("Initiating Driver.")

            #Styart the driver function that is part of the component.
            #Driver will be defined to set up further events for the network and test or executre functionality. 
            Timer(1, self.driver)


        # Event handler called when POX goes into up state
        # (we actually listen to the event in launch() below)
        log.info("Skeleton application ready (to do nothing).")
        controller = self
        #t1 = threading.Thread(target=con_check) 
        Timer(2, con_check)
```
Using the go_up event, I need to then see if all connections have been established before I continue. 
If I use time.sleep, the usual blocking operation, it works perfectly, but interferes with the recoco tasks which handle connections going up, and sometimes misses them. This is the most functional method available. 

Using yield recoco.Sleep(1), nothing happens. Go_up does nothing and no input is even run, it simply just does not happen. 

Calling faux_Sleep(1) to call recoco.Sleep in a separate function does nothing either, and the loop repeats quickly with no delay at all, indicating sleep is not working. 

I've looked at the package which contains Sleep multiple times, as well as the blocking function it inherits from, and nothing has indicated what might be the issue. If I'm not mistaken, using the timer is indeed a recoco function which should work with these blocking operations, but nothing has been functional as expected so far. Please advise.

**Comment by nskjellum** [comment]
I'll see if I can provided some more information here. 

Goal: Several functions I need to wait to see if a particular packet has successfully been delivered. As I expect to do this multiple times through one execution and have to return values, it would be convenient if I could do this all in one function over breaking it down into a chain of timed functions for each step. 

Branch - Halosaur
Log.debug - No errors apparent when running, connections run smoothly. The yield recoco.Sleep(N) doesn't play nice with my program as I frequently am returning values back which breaks when I have to loop yield-Sleep commands. 

I believe the rest of the information I've described sufficiently covers the behavior and example portions.

**Comment by nskjellum** [comment]
Uncertain if I'm testing this right, but the recoco scheduler doesn't seem to be executing any of the blocking functions. I added a print statement for recoco.Sleep to see if it was even working (because init definitely happens) as below. '
```
class Sleep (BlockingOperation):
  """
  Sleep for specified amount of time (seconds)
  None means unscheduler (i.e., sleep until an outside force wakes it)
  0 means reschedule for later (no additional time)
  """
  def __init__ (self, timeToWake = None, absoluteTime = False):
    if absoluteTime == False and timeToWake != None: timeToWake += time.time()
    self._t = timeToWake

  def execute (self, task, scheduler):
    print("Sleep executed!")
    if self._t is None:
      # Just unschedule
      return
    if self._t == 0 or self._t < time.time():
      # Just reschedule
      scheduler.fast_schedule(task)
      return
    scheduler._selectHub.registerTimer(task, self._t, True) # A bit ugly

```
And then I ran a test program to see if it would show up. 

```
python3.9 pox.py log.level --DEBUG sleep --foo=foo
POX 0.8.0 (halosaur) / Copyright 2011-2022 James McCauley, et al.
WARNING:sleep:Foo: foo (<class 'str'>)
WARNING:sleep:Bar: False (<class 'bool'>)
DEBUG:boot:Not launching of_01
DEBUG:core:POX 0.8.0 (halosaur) going up...
DEBUG:core:Running on CPython (3.9.19/Apr 6 2024 17:57:55)
DEBUG:core:Platform is Linux-6.8.0-40-generic-x86_64-with-glibc2.35
INFO:sleep:Skeleton application ready (to do nothing).
DEBUG:sleep:Hey, are we gonna sleep or what?
DEBUG:sleep:Hey, are we gonna sleep or what?
DEBUG:sleep:Hey, are we gonna sleep or what?
DEBUG:sleep:Hey, are we gonna sleep or what?
DEBUG:sleep:Hey, are we gonna sleep or what?
INFO:core:POX 0.8.0 (halosaur) is up.
^CINFO:core:Going down...
INFO:core:Down.
```
No dice, something seems wrong with the scheduler, though I hesitate to be authoritative on that since the rest of POX's events for handling switches have worked without a problem. '

Is there a way to arbitrarily initiate normal threads without stopping recoco processes? Otherwise I think this program is virtually nonfunctional for my purposes and I need to be able to block within the controller.

**Comment by nskjellum** [comment]
Hello. 

I took this week to see if I could discern the problem, and figured it out quickly thanks to your example. 

I was not using the recoco.task class when doing my work. I am used to these blocking primitives working without explicit threading but it didn't occur to me this may not be the case for recoco. After testing with the following code and the skeleton launch function, it worked perfectly. 

```
class time_task(Task):

    def __init__(self, time):
        self.time = time
        Task.__init__(self)
        log.info("Times up in task land!")


    def run(self):
        yield Sleep(2)
        log.info("Honk Shoo.")

def times_up():
    log.info("Times Up!")

def _go_up (event):
    # Event handler called when POX goes into up state
    # (we actually listen to the event in launch() below)
    log.info("Skeleton application ready (to do nothing).")

 #   log.info("We are going to sleep now.")
    try:

        t = time_task(2)
        t.start()
        #pass
       # yield recoco.Sleep(2)
        #recoco.Sleep(2)
        #recoco.Timer(2, times_up)
    except:
        log.info("Hey! This is throwing an exception!")

#    log.info("If you saw this instantly, it didn't work!")

```

I recommend for future users that there is an explicit guide for the recoco section which mentions the necessity of creating a new class which inherits from task, or at least cites the specific examples in that section. Now that I have this at my disposal, I think this issue is closed for me. Thank you for your assistance.

**Comment by MurphyMc** [comment]
Yes, this has never been very well documented.  The new POX ichthyosaur comes with [a new example component](../blob/ichthyosaur/pox/lib/recoco/example_task.py) that I believe covers the material you were missing.  Sorry it hasn't been there for years already; I hope it helps future users.
