### ISSUE TITLE
IPv6 support in Open vSwitch

### ISSUE THREAD

**Issue by samrussell** [noxrepo/pox#35]
I've not had a chance to delve into the details, but it looks like OVS now supports enough of OpenFlow 1.2 to handle IPv6 flows (and I'm told that the latest Pica8 implementation for the Pronto switches supports this too) - http://openvswitch.org/cgi-bin/gitweb.cgi?p=openvswitch;a=commit;h=aa6305ea678ab889d7418c90371c72ead2c8e1e8

What do people think is the best way to handle this in POX? It looks like it'll need a minimum amount of OpenFlow 1.2 - is it worth implementing enough to do IPv6 flows as a special case and leave the rest for the current 1.0 implementation?

**Comment by MurphyMc** [comment]
Support for higher OpenFlow versions is a good goal, and I've started putting some more serious thought into how to do this right in POX now that they've gotten more serious about doing it in OVS.  But last I checked, OVS was still a ways off from full 1.1 support, and 1.2 was even further.  I don't have that much interest in having it in POX before it's pretty fleshed out in OVS, and _I_ don't have time for this for the Summer2012 milestone anyway.  If someone _else_ wants to get serious about adding 1.1 or 1.2 support and getting it into the repository, I'd suggest contacting me or posting on the pox-dev mailing list before you start.

If the goal is just to get IPv6 in POX... this has been available in OVS via an extension to 1.0 for quite a while, I think (v1.1.0?).  I haven't had a use case (nor has anyone come to me with one), so I haven't really looked, but I think it's just done with the flexible match extension.  This seems like the right place to start for now… code written for flexible match should be applicable to higher OF versions anyway. Again, I don't have time for this immediately, but would work with someone who did.  I think the major parts of the problem are: 1) Adding the OpenFlow extension(s), 2) Proposing how to handle IPv6 addresses in pox.lib.addresses and implementing that, 3) Adding an ipv6 class to pox.lib.packet.

**Comment by MurphyMc** [comment]
Just a note that the recently added support for Nicira extensions in betta is relevant to this.

Some stuff that's still missing: IP6Addr in lib.addresses, and IP6 support in lib.packet.  I have some code for both of these kicking around somewhere, I think, but nothing finished.

**Comment by MurphyMc** [comment]
It's just a first pass, but the three referenced commits add IPv6 support throughout POX, so I'm going to close this.

Problems with them or additional feature requests should be new issues.

**Comment by SilviaFc** [comment]
Can you explain me how to update pox to use with IPv6?
in the directory /pox/pox/lib/packets I've only ipv4 files. 
Thanks

**Comment by MurphyMc** [comment]
You have to be on the current development branch -- carp.

git checkout carp
