### ISSUE TITLE
Get IP from switch socket connection

### ISSUE THREAD

**Issue by festradasolano** [noxrepo/pox#37]
Hello. Please help me with this issue. I need to retrieve the IP from a switch socket connection. I found that there is a socket for each switch connection in the connections list (i.e. core.components.get("openflow")._connections). However, I can't get the IP from this socket. How can I do that? Is there another way to do that? Thanks!!

**Comment by MurphyMc** [comment]
This should be a plain Python socket object.  As per the documentation in http://docs.python.org/library/socket.html you should just be able to call .getpeername() on it.

Also, please note that the pox-dev mailing list is the correct place for this sort of discussion.  We're using the issue tracker to track bugs and feature suggestions in POX itself, whereas this is more of a help request.
