### ISSUE TITLE
No support for strip VLAN?

### ISSUE THREAD

**Issue by basus** [noxrepo/pox#39]
It seems like `libopenflow_01.py` is missing support for the strip VLAN action. Is there some way to easily add this or use `ofp_action_vlan_vid` to have the same effect?

**Comment by MurphyMc** [comment]
I think you can use ofp_action_vlan_vid to set the VLAN to 0xffff or something and that has the same effect (check the spec).  You can also just create a generic ofp_action_header and set its type to OFPAT_STRIP_VLAN (something like fm.actions.add(of.ofp_action_header(type=of.OFPAT_STRIP_VLAN))).

But, I've just pushed an update to libopenflow in the betta branch which has an explicit ofp_action_strip_vlan, so I'm closing this issue.  If you try it and it has problems, feel free to reopen. :)
