### ISSUE TITLE
l2_multi blackholes traffic whenever hosts migrate

### ISSUE THREAD

**Issue by colin-scott** [noxrepo/pox#45]
Just bumped into what seems to be an unimplemented scenario in l2_multi.

Suppose all hosts in the network ping each other, l2_multi correctly learn locations, and sets up   up all-to-all paths. Then a host migrates to a new ingress switch, and sends one packet. l2_multi learns its new location, and sets up a path for that new packet.

The problem is that l2_multi _does not_ appear to update the previously installed paths leading to the old host's migrations. In other words, traffic destined towards that host blacholes until the flow mods time out.

**Comment by MurphyMc** [comment]
Yup.  But it's just an example, not a real solution for forwarding in the wild.

As with the other l2_multi issue, the real way to resolve this is to model desired switch state in the controller, which just isn't what l2_multi aims to do.  One could minorly improve things by, for example, always installing paths symmetrically (I think I actually have a version somewhere which does this), but it'd still just be a hack IMO.

**Comment by colin-scott** [comment]
Gotcha. Out of curiosity, what are the most ready-for-the-wild modules in POX? (or, do you know of third-party applications built on POX?)

Thanks!

**Comment by MurphyMc** [comment]
I think 118edac42e4f78be6df358c8da1bc746ca54f776 sort of addresses this since it now sets up paths in both directions every time.

None of the forwarding components that come with POX are really meant for use in production.  RouteFlow uses POX to communicate with switches, though, and I do think it's fairly production-worthy...
