### ISSUE TITLE
syntax error in of_json.py

### ISSUE THREAD

**Issue by nomorecaddy** [noxrepo/pox#60]
Hi, I'm trying to use the webservices application on pox.  However, I get a syntax error in of_json.py

Could you point me in the right direction?

[root@papa pox]# ./pox.py  openflow.webservice web.webcore
./pox.py: line 38: type: python2.7: not found
POX 0.1.0 (betta) / Copyright 2011-2013 James McCauley, et al.
Traceback (most recent call last):
  File "/opt/oess-1.0.6/pox/pox/boot.py", line 89, in do_import2
    **import**(name, globals(), locals())
  File "/opt/oess-1.0.6/pox/pox/openflow/webservice.py", line 53, in <module>
    from pox.openflow.of_json import *
  File "/opt/oess-1.0.6/pox/pox/openflow/of_json.py", line 111
     _unfix_map = {k:_unfix_null for k in of.ofp_match_data.keys()}
                                   ^
 SyntaxError: invalid syntax
Could not import module: openflow.webservice

**Comment by MurphyMc** [comment]
Can you post the complete output from "./pox.py log.level --DEBUG" ?

**Comment by nomorecaddy** [comment]
Hi, actually right after I posted this, I thought maybe the information in the very first line of output is significant:
./pox.py: line 38: type: python2.7: not found
I think my system was running Python 2.6.6, so I installed 2.7, and just like that, I was up and running with webservices!  
Sorry for the false alarm

**Comment by MurphyMc** [comment]
Yeah, I was figuring that was the case.  "./pox.py" should actually have given a proper log message that you should upgrade, not just that weird message at the top (the appearance of which is actually a recent and now corrected bug).

Glad you got it working.
