### ISSUE TITLE
standalone datapath problems on Windows

### ISSUE THREAD

**Issue by damomeen** [noxrepo/pox#67]
Hi,

I have downloaded the latests carp branch in order to test your last commits (many thanks for that work!). I'm trying to run "plain" version on Windows7.

First I have started Pox controller (python pox.py --verbose) and then 'plain' datapath (python pox.py --no-openflow -
-verbose datapaths:softwareswitch --addr=127.0.0.1)

Log from Pox controller:

> C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp>python pox.py --verbose
> POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
> DEBUG:core:POX 0.2.0 (carp) going up...
> DEBUG:core:Running on CPython (2.7.3/Apr 10 2012 23:24:47)
> DEBUG:core:Platform is Windows-7-6.1.7601-SP1
> INFO:core:POX 0.2.0 (carp) is up.
> DEBUG:openflow.of_01:Listening on 0.0.0.0:6633
> ERROR:openflow.of_01:Exception reading connection [None 1]
> Traceback (most recent call last):
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\openflow\of_01.py
> ", line 905, in run
>     if con.read() is False:
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\openflow\of_01.py
> ", line 724, in read
>     d = self.sock.recv(2048)
> error: [Errno 10053] Connection establishment was cancelled by the host. (my translation from Polish).
> INFO:openflow.of_01:[None 1] closed

Log from Pox 'plain' datapath:

> C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp>python pox.py --no-openflow -
> -verbose datapaths:softwareswitch --addr=127.0.0.1
> POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
> DEBUG:lib.ioworker:RecocoIOWorker.send_fast() not available
> DEBUG:core:POX 0.2.0 (carp) going up...
> DEBUG:core:Running on CPython (2.7.3/Apr 10 2012 23:24:47)
> DEBUG:core:Platform is Windows-7-6.1.7601-SP1
> DEBUG:dp.00-00-00-00-00-01:Attempting to connect to 127.0.0.1:6633
> ERROR:lib.ioworker.workers:Couldn't connect to 127.0.0.1:6633
> Traceback (most recent call last):
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\boot.py", line 46
> 4, in boot
>     core.goUp()
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\core.py", line 32
> 1, in goUp
>     self.raiseEvent(UpEvent())
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\lib\revent\revent
> .py", line 281, in raiseEvent
>     rv = event._invoke(handler, _args, *_kw)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\lib\revent\revent
> .py", line 159, in _invoke
>     return handler(self, _args, *_kw)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\datapaths__init_
> _.py", line 88, in up
>     max_retry_delay=max_retry_delay, switch=switch)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\lib\ioworker\work
> ers.py", line 165, in begin
>     w = cls(**kw)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\datapaths__init_
> _.py", line 32, in __init__
>     super(OpenFlowWorker, self).**init**(switch=switch,**kw)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\lib\ioworker\work
> ers.py", line 193, in **init**
>     super(BackoffWorker,self).**init**(**kw)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\lib\ioworker\work
> ers.py", line 129, in **init**
>     self._make_connection(**kw)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\lib\ioworker\work
> ers.py", line 152, in _make_connection
>     raise RuntimeError("Couldn't connect")
> RuntimeError: Couldn't connect

I also find another bug when I have started Pox datapath with additional argument:

> C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp>python pox.py --no-openflow -
> -verbose datapaths:softwareswitch --addr=127.0.0.1 --dpid=1
> POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
> DEBUG:lib.ioworker:RecocoIOWorker.send_fast() not available
> Traceback (most recent call last):
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\boot.py", line 46
> 2, in boot
>     if _do_launch(argv):
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\boot.py", line 20
> 2, in _do_launch
>     f(**params)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\datapaths__init_
> _.py", line 106, in softwareswitch
>     do_launch(SoftwareSwitch, addr, port, max_retry_delay, dpid)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp\pox\datapaths__init_
> _.py", line 73, in do_launch
>     dpid = str_to_dpid(dpid)
> NameError: global name 'str_to_dpid' is not defined

**Comment by damomeen** [comment]
I'm testing Pox from Windows because it is my native OS. However, I have no plans to really deploy it in Windows (only Linux). But if I can easily perform some tests...

> C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp>python pox.py --no-openflow -
> -verbose datapaths:softwareswitch --addr=127.0.0.1 --dpid=1
> POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
> DEBUG:lib.ioworker:RecocoIOWorker.send_fast() not available
> DEBUG:core:POX 0.2.0 (carp) going up...
> DEBUG:core:Running on CPython (2.7.3/Apr 10 2012 23:24:47)
> DEBUG:core:Platform is Windows-7-6.1.7601-SP1
> DEBUG:dp.00-00-00-00-00-01:Attempting to connect to 127.0.0.1:6633
> INFO:dp.00-00-00-00-00-01:Disconnected
> INFO:core:POX 0.2.0 (carp) is up.
> DEBUG:dp.00-00-00-00-00-01:disconnected
> DEBUG:dp.00-00-00-00-00-01:Try again in 1 seconds
> DEBUG:dp.00-00-00-00-00-01:Attempting to connect to 127.0.0.1:6633
> INFO:dp.00-00-00-00-00-01:Disconnected
> DEBUG:dp.00-00-00-00-00-01:disconnected
> DEBUG:dp.00-00-00-00-00-01:Try again in 2 seconds
> DEBUG:dp.00-00-00-00-00-01:Attempting to connect to 127.0.0.1:6633
> INFO:dp.00-00-00-00-00-01:Disconnected
> DEBUG:dp.00-00-00-00-00-01:disconnected
> DEBUG:dp.00-00-00-00-00-01:Try again in 4 seconds
> INFO:core:Going down...
> INFO:core:Down.
> 
> C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp>python pox.py --verbose
> POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
> DEBUG:core:POX 0.2.0 (carp) going up...
> DEBUG:core:Running on CPython (2.7.3/Apr 10 2012 23:24:47)
> DEBUG:core:Platform is Windows-7-6.1.7601-SP1
> INFO:core:POX 0.2.0 (carp) is up.
> DEBUG:openflow.of_01:Listening on 0.0.0.0:6633
> INFO:openflow.of_01:[None 1] Connection reset
> INFO:openflow.of_01:[None 1] closed
> INFO:openflow.of_01:[None 2] Connection reset
> INFO:openflow.of_01:[None 2] closed
> INFO:openflow.of_01:[None 3] Connection reset
> INFO:openflow.of_01:[None 3] closed

**Comment by MurphyMc** [comment]
I appreciate the help.  I don't have Windows easily available.

What happens if you comment out the setblocking call in lib/ioworker/works.py line 144?

**Comment by damomeen** [comment]
Commented and works.

> C:\Users\DamianP-PCSS\Downloads\pox-carp2\pox-carp>python pox.py --no-openflow -
> -verbose datapaths:softwareswitch --addr=127.0.0.1 --dpid=1
> POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
> DEBUG:lib.ioworker:RecocoIOWorker.send_fast() not available
> DEBUG:core:POX 0.2.0 (carp) going up...
> DEBUG:core:Running on CPython (2.7.3/Apr 10 2012 23:24:47)
> DEBUG:core:Platform is Windows-7-6.1.7601-SP1
> DEBUG:dp.00-00-00-00-00-01:Attempting to connect to 127.0.0.1:6633
> INFO:dp.00-00-00-00-00-01:Disconnected
> INFO:core:POX 0.2.0 (carp) is up.
> DEBUG:lib.ioworker:Resetting rx_handler on <pox.datapaths.OpenFlowWorker object
> at 0x000000000313D748>?
> INFO:dp.00-00-00-00-00-01:Connected to controller
> DEBUG:sw1:Got OFPT_HELLO with XID 1
> DEBUG:sw1:Sent hello
> DEBUG:sw1:Got OFPT_FEATURES_REQUEST with XID 2
> DEBUG:sw1:Got OFPT_SET_CONFIG with XID 3
> DEBUG:sw1:Got OFPT_FLOW_MOD with XID 4
> DEBUG:sw1:Flow mod details: header:
>   version: 1
>   type:    14 (OFPT_FLOW_MOD)
>   length:  72
>   xid:     4
> match:
>   wildcards: nw_tos|tp_dst|dl_dst|dl_src|in_port|dl_vlan_pcp|nw_proto|dl_vlan|tp
> _src|dl_type|nw_src(/0)|nw_dst(/0) (1110000010000011111111 = 3820ff)
> cookie: 0
> command: 3
> idle_timeout: 0
> hard_timeout: 0
> priority: 32768
> buffer_id: None
> out_port: 65535
> flags: 0
> actions:
> DEBUG:sw1:Got OFPT_BARRIER_REQUEST with XID 5

**Comment by damomeen** [comment]
Downloaded the last carp branch and works fine. Thank you.

**Comment by MurphyMc** [comment]
Glad to hear it!
