### ISSUE TITLE
support cookies in ofp_match

### ISSUE THREAD

**Issue by cl4u2** [noxrepo/pox#71]
Please add support for matching cookies to class ofp_match.

This could be useful to match set of rules (e.g. for removal) without keeping an history of inserted rules in the controller.

**Comment by MurphyMc** [comment]
I agree this would be useful, but it's not supported by OpenFlow 1.0, so there's nothing I can do about it as far as the ofp_match in the 1.0 version of libopenflow.

On the other hand, if you're using Open vSwitch, you can do this using the extended Nicira match, nx_match and nx_flow_mod which are in openflow.nicira.

OpenFlow 1.2 should be similar, but POX doesn't have support for it yet.
