### ISSUE TITLE
OFP_DEFAULT_MISS_SEND_LEN=128 is too small

### ISSUE THREAD

**Issue by changbl** [noxrepo/pox#93]
In pox/openflow/libopenflow_01.py, OFP_DEFAULT_MISS_SEND_LEN is set to default 128, which is too small for packets like DHCP.  

Also this is documented at: http://ikimi.net/?p=131

Change it to default 1500 will be fine for Ethernet packets. We have tested this setting.

**Comment by MurphyMc** [comment]
This value is from the specification, so I am not planning to change it.  However, it can be overridden by sending an OFPT_SET_CONFIG message, or by installing a table entry that sends packets you're interested in (possibly all of them) to the controller with a larger size specified.

POX includes a component specifically to do the former for you automatically -- misc.full_payload.  This has been documented in the manual wiki under the section "What are these log messages from the packet subsystem?" but now has an entry in the components section as well.

**Comment by changbl** [comment]
Thanks for pointing this out.

Thanks

Changbin
