### ISSUE TITLE
subscribing to OFPT_FLOW_MOD messages

### ISSUE THREAD

**Issue by nomorecaddy** [noxrepo/pox#95]
Hi, I'm trying to write my own module in the ext directory that listens for OFPT_FLOW_MOD messages going from the POX controller to switches.  I notice there are a lot of events already built in the core like ConnectionUp, PortStatus, etc., but I didn't see an event that would fire on adding and deleting flows.

Basically, I need to keep track of what flows have been added and deleted using the webservices module.  I guess I could copy the module to ext and make my changes, but I wanted to explore this solution first.

thanks

**Comment by MurphyMc** [comment]
Yes, the current events all correspond to messages that come _from_ the switches, with the assumption that you are already in control of things you're sending _to_ switches.  The way the low-level API currently works (which is what basically everything uses), there's no amazingly good way to add this feature (events based on outgoing messages).

So I think you're going to be hacking up the webservices module.  However, I'd point out that this is Python -- you may not need to copy the module at all just to hack on it.  You may be able to replace individual functions on it (the ones that do flow_mods) from the outside which wrap the real functions.  You may also be able to create your own version of the webservices module not by copy/paste but by importing the old one and subclassing pieces.  If reasonable changes to the original module would make this easier (perhaps it should have its own internal send functions which create and send messages which could then be easily overridden, for example), feel free to bring them up for discussion or submit a PR.

**Comment by MurphyMc** [comment]
Closing this.  Feel free to reopen if there's more.
