### ISSUE TITLE
Adding a Flow Table Entry using Openflow in POX

### ISSUE THREAD

**Issue by MJ8623** [noxrepo/pox#96]
Hello,
I need to add a flow entry on a switch in the openflow.py file in POX. How do I do it?

**Comment by MurphyMc** [comment]
The section of the POX manual on working with OpenFlow discusses adding flows.  So does the OpenFlow Tutorial.  There are links to both of these on the POX documentation page: http://www.noxrepo.org/pox/documentation/

Additionally, POX comes with many examples which show installing flows.  For example, forwarding/hub.py is a simple one.

If you have problems not addressed in any of the above, I'd suggest you ask for help on the POX forum or pox-dev mailing list on noxrepo.org.  If you do, I'd suggest you included additional information (for example, clarify why you need to do it in openflow.py).  There are tips on doing this in the last entry of the FAQ in the manual.

**Comment by MJ8623** [comment]
Hello Again,
                 Thank you very much for the suggested reading. However, I still feel that I need some help. My question specifically is this,
-- As soon as a new port is added to a switch, I want to update the flow tables in all of the switches in the network. Hence I am doing it in add_port() of openflow.discovery.py.
-- I am able to find the interface mac address of the switch where the new port was added. But, I am not able to find out which host is connected to that port.
-- I guess if I have both the mac addresses, I will be able to update the flow tables.

```
              Please help me on this. Thank you.
```

**Comment by MurphyMc** [comment]
If what you want is to do something whenever a port is added, doing it by modifying openflow.discovery is probably ill-advised.  You'd be better off just writing a handler for the PortStatus event on core.openflow (which is what discovery does internally, along with handling ConnectionUp).

OpenFlow doesn't magically know which host is attached to a port.  Components like l2_learning and host_tracker do this by watching packets (via a PacketIn handler).  It's also possible to use information from other sources (e.g., a cloud management system).

Just a note: the MAC addresses of the switch ports are not usually useful.

**Comment by humikahout** [comment]
How i find output port of my custom topology for adding flow in pox.
I dont now which output port is use for adding flow
